Opetushallitus/ehoks

src/db/migration/V1_1554888506062__Create_database.sql
src/oph/ehoks/db/postgresql.clj
src/oph/ehoks/db/queries.clj

Tietokannan taulujen nimien lyhentäminen.
Huomaa, että tämä muuttaa ensimmäistä migraatiota.

Truncate long table names

---

src/oph/ehoks/handler.clj
src/oph/ehoks/middleware.clj
src/oph/ehoks/oppija/auth_handler.clj
src/oph/ehoks/oppija/handler.clj
src/oph/ehoks/oppija/opintopolku.clj
test/oph/ehoks/oppija/auth_handler_test.clj
test/oph/ehoks/oppija/opintopolku_test.clj
test/oph/ehoks/utils.clj

Siirretään oppijan tunnistautuminen oppijan nimiavaruuteen.
Tämä vaatii muutokset fronttiin:
`/ehoks-backend/api/v1/session/*` -> `/ehoks-backend/api/v1/oppija/session/*`
ja 
Shibbolethiin:
`/ehoks-backend/api/v1/session/opintopolku/` -> `/ehoks-backend/api/v1/oppija/session/opintopolku/`
Vanhat endpointit toimii vielä toistaiseksi, mutta niitä ei nää enää swaggerin kautta. Tätä ei versioitu, koska endpointeja ei käytä, kuin meidän sisäiset järjestelmät.

Eh 168 move oppija

---

src/db/migration/V1_1559718030330__Add_tarkentavat_tiedot_arvioija_fkey_for_oopto_and_ooyto.sql

olemassa_olevat_ammatilliset_tutkinnon_osat taululla oli viittaus todennettu_arviointi_lisatiedot tauluun. Lisätty sama viittaus myös olemassa_olevat_paikalliset_tutkinnon_osat ja olemassa_olevat_yhteiset_tutkinnon_osat tauluille.

Added migration for tarkentavat_tiedot_arvioija foreign key for

---

resources/db/oppijat/select_oppilaitos_oppijat.sql
resources/dev/src/oph/ehoks/dev_tools.clj
src/db/migration/V1_1571210000601__Remove_tutkinto_and_osaamisala.sql
src/oph/ehoks/common/schema.clj
src/oph/ehoks/oppijaindex.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/oppijaindex_test.clj
test/oph/ehoks/user_test.clj
test/oph/ehoks/virkailija/handler_test.clj

Poistettu opiskeluoikeudelta tutkinto osaamisala kentät koska niitä ei tarvittu enää mihinkään.

Eh 605 tutkinto and osaamisala remove

---

src/oph/ehoks/logging/audit.clj
src/oph/ehoks/virkailija/handler.clj

Lisätty :put metodi audit.clj:hin ja sille oma operation overwrite. Lisäksi lisätty virkailijan handleriin post, put ja patch :audit {:new ...}, jotta myös changes tulee logille.

Eh 668 add oid to audit logs

---

src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/hoks/hoks.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/hoks/handler_test.clj
test/oph/ehoks/virkailija/handler_test.clj

Lisätty siis put-kutsujen hanskaukseen vaan yksi selvitys, missä katsotaan, yritetäänkö päivittää opiskeluoikeus-oidia ja jos yritetään (eli lähetetty oid on eri kuin olemassaoleva oid), niin päräytetään virhe. Ja sama homma sitten oppija-oidille, kun eihän sitäkään saa korvata.

Eh 733 opiskeluoikeus not allowed to update

---

src/oph/ehoks/external/oppijanumerorekisteri.clj
test/oph/ehoks/external/oppijanumerorekisteri_test.clj

Jos oppijanumerorekisteristä palautui null-arvoja yhteystietoihin liittyen, vastaus ei mennyt skeemavalidoinnista läpi joten nyt filtteröidään null tiedot pois ja jos koko contact groupin arvot ovat nullia karsitaan group vastauksesta pois.

Student info fix

---

resources/db/hoksit/select_count_all_hoksit.sql
src/oph/ehoks/db/db_operations/hoks.clj
src/oph/ehoks/db/queries.clj
src/oph/ehoks/oppijaindex.clj
src/oph/ehoks/virkailija/schema.clj
src/oph/ehoks/virkailija/system_handler.clj
test/oph/ehoks/virkailija/handler_test.clj

Tässä branchissa siis apit sitä varten, että ylläpitovälilehdelle saa näytettyä hoksien koko lukumäärän sekä haettua opiskeluoikeudella hoks-id:n, kun tätä asiakas on paljon kysellyt (ja sitten mä kaivelen näitä tuotannon kannasta). 
Pistin nämä systemhandleriin, kun siinä on näppärästi ne superuser-oikat tarkastettuna ja tämähän on vaan oph-pääkäyttäjä-oikille tarkoitettu. Muuten käytetään aikalailla olemassaolevia juttuja, yhden queryn kirjoitin kans.
(Frontin muutokset ovat branchissa new-buttons-for-yllapito, josta teen oman pr:n aikanaan. )

New api for yllapito

---

doc/hoks.md
resources/dev/demo-data/hoksit.json
resources/dev/dev-routes/rest_codeelement_ravintolakokinatjarjestys__4_2.json
src/oph/ehoks/hoks/aiemmin_hankitut.clj
src/oph/ehoks/hoks/hankittavat.clj
src/oph/ehoks/hoks/schema.clj

Removed share uuid from schema for now as it needs to be added only for GET schemas. Total removal of share uuid was faster than removing from PUT, PATCH, POST schemas and also share functionality feature isn't developed currently.

Eh 851 share id removal

---

src/db/migration/V1_1586954509834__Add_hankintakoulutus_info_to_opiskeluoikeus.sql
src/oph/ehoks/external/koski.clj
src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/oppijaindex.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/hoks/handler_test.clj
test/oph/ehoks/hoks/hoks_test_utils.clj
test/oph/ehoks/oppijaindex_test.clj
test/oph/ehoks/utils.clj
test/oph/ehoks/virkailija/handler_test.clj

Lisätty hoksien luontiin steppi missä lisätään mahdolliset hankintakoulutus-opiskeluoikeudet kantaan. Erottelu muista opiskeluoikeuksista sen perusteella, että hankintakoulutuksissa kannassa on järjestäjän ja opiskeluoikeuden oidit. Rajapinta näiden hakemiselle on varmaan parempi tehdä kunhan näitä tarvitaan käytännössä.

Eh 889 hankintakoulutuksen toteuttaja

---

src/db/migration/V1_1590752147461__Add_hoks_id_to_shared_modules.sql
src/oph/ehoks/oppija/schema.clj
test/oph/ehoks/oppija/share_handler_test.clj

Jakolinkkiä luodessa vaaditaan nyt myös hoksin eid, jotta linkkiin liittyvien tietojen hakeminen myöhemmin olisi helpompaa.

Eh 980 jakolinkkitauluun hoks

---

src/oph/ehoks/virkailija/system_handler.clj

Huomasin, että tuossa edellisessä mergetyssä haarassa eh-1034 oli sittenkin virhe system-handlerissa, jossa käytettiin oid query paramsina, vaikka urlissa oli opiskeluoikeus-oid. Lisäksi kutsuttiin oppijaindeksin päivitystä, vaikka piti päivittää opiskeluoikeusindeksiä.

Eh 1034 fix update opiskeluoikeus

---

src/oph/ehoks/oppija/schema.clj
src/oph/ehoks/oppija/share_handler.clj
test/oph/ehoks/oppija/share_handler_test.clj

Vaihdettiin sharehandlerin palautettavaksi arvoksi objekti arrayn sijaan, koska jaettavia osaamisen-osoittamisia tai osaamisen-hankkimistapoja on aina vain yksi.

Eh 981 return object for share info

---

src/oph/ehoks/oppija/auth_handler.clj
test/oph/ehoks/oppija/auth_handler_test.clj

Oppijan cas-kirjautumiseen tarkastelu onko cas:n lähettämä ticket mennyt validoinnista läpi ja poikkeuksen heittäminen jos ei. Laitettu cas-kirjautumisen endpoint aktiiviseksi koska ei päästä enää etenemään jos cas:n validointi ei ole mennyt läpi. Endpoint nimettävä uudelleen kunhan cas-oppija otetaan käyttöön ja shibboleth kirjatuminen poistetaan.

Eh 984 cas oppija error handling

---

src/oph/ehoks/external/aws_sqs.clj
src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/virkailija/handler.clj

- Muutettu uudelleenlähetyksen logiikka käyttämään kyselylinkkejä avainten päättelyn sijaan
- Lähetysdatan paych palauttaa 404 jos kyselylinkkiä ei löydy kannasta
- Lisätty tuplavarmistus sqs-viestien lähetyksen onnistumisesta (jos paluu arvossa ei ole messageId:tä, viestin jonoon asettamisessa on tapahtunut jotain outoa, mutta jos id löytyy viesti on jonossa normaalisti. Aws-sdk:n sqs-clientin pitäisi heittää virhettä tälläisissä tilanteissa, mutta puuttuvien herätteiden tutkimisesta on jäänyt tunne että viestejä on kadonnut jonnekin)

Eh 1001 uudelleenlähetys

---

resources/dev/src/oph/ehoks/mocked_routes/mock_auth_routes.clj
src/oph/ehoks/oppija/auth_handler.clj
src/oph/ehoks/oppija/settings_handler.clj
test/oph/ehoks/oppija/settings_handler_test.clj

Oppijan sessioon tallennettiin oppijan tiedot eri kenttien nimillä kuin mitä bäkkärin skeemassa on. Nimetty kentät skeeman mukaiseksi. Lisätty vielä yksi puuttuva caller-id pakotus.

Eh 984 cas oppija refinement

---

resources/dev/ehoks-oph.properties
resources/dev/src/oph/ehoks/mocked_routes/mock_auth_routes.clj
resources/prod/ehoks-oph.properties
src/oph/ehoks/misc/handler.clj
src/oph/ehoks/misc/schema.clj
src/oph/ehoks/oppija/auth_handler.clj

Lisätty logout route cas-oppijalle. Korjattu onnistuneen cas-kirjautumisen jälkeinen redirect ehoksin etusivulle, prod konfiguraatiossa käytettiin frontin hostnamen sijasta bäkkärin. Tähän redirectiin pitäisi mahdollisesti tehdä vielä localen päättely jotta studieinfo:sta ei kirjautumisen jälkeen päädytä opintopolkuun.

Eh 984 cas oppija logout

---

resources/dev/src/oph/ehoks/mocked_routes/mock_auth_routes.clj
resources/dev/src/oph/ehoks/mocked_routes/mock_oppijanumerorekisteri_routes.clj
src/oph/ehoks/misc/handler.clj

Korjattu cas-oppija kirjautuminen. Cas callback urlin lopusta puuttui kauttaviiva mikä aiheutti route not found virheen.

Eh 984 cas oppija login fix

---

src/oph/ehoks/external/aws_sqs.clj

Tämä ei vaikuta nykyisen portaalin toimintaan, mutta siitä tulee tärkeä, kun tehdään EH-1304.

Korjattu pikkuvirhe

---

doc/hoks.md
src/db/migration/V1_1655906245465__Opetus_ja_ohjaus_maara_tyyppi.sql
test/oph/ehoks/hoks/hoks_parts/parts_test_data.clj

- vaihdettu opetus_ja_ohjaus_maara double precisionista decimal/numericiksi
- generoitu tietomallin markdown lein gendoc:lla

Opetus ja ohjaus maara tietotyypin vaihdos

---

resources/dev/src/oph/ehoks/import.clj

Importing dummy data wasn't working because some HOKS date values were having type `character varying` when they were being inserted to the DB.

Fix broken dummy data import functionality

---

src/oph/ehoks/db/db_operations/db_helpers.clj
src/oph/ehoks/db/db_operations/hoks.clj
src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/hoks/hoks.clj
src/oph/ehoks/hoks/vipunen_schema.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/hoks/hoks_test_utils.clj

https://jira.eduuni.fi/browse/OY-3912
Muutos: Päivitetään `updated_at` aikaleima HOKSin passivoinnin yhteydessä. Tämä mahdollistaa passivoitujen HOKSien siirron Vipusen käyttämän delta-rajapinnan kautta. Passivoiduilla HOKSeilla näkyy nyt delta-rajapinnassa `poistettu`-kenttä.

OY-3912 Extend vipunen endpoint to return shallow deleted hokses

---

src/oph/ehoks/external/eperusteet.clj
src/oph/ehoks/oppija/oppija_external.clj
src/oph/ehoks/virkailija/external_handler.clj
test/oph/ehoks/external/eperusteet_test.clj

Bugi: TUVA-HOKSiin tallennetun koulutuksen osan nimi ei näy
- lisätty puuttuva rajapinta oppijan puolelle
- korjattu eperusteet-palvelun virheenkäsittely virkailijan puolen rajapintaan
- eperusteiden data on julkaistu uudelleen, korjasi "puuttuneet" koulutuksenosatuva-koodit

OY-3885: Handle not found eperusteet data

---

src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj

Tämä on musta siistein tapa testata määrittämällä rajoitteet skeemassa.  Ainoa huono puoli on se, että (LocalDate/now):n kaltaiset funktiot ovat sivuvaikutuksellisia, jolloin skeemallakin on eräänlainen tila: joskus skeemavalidointi epäonnistuu ja parin päivän päästä onnistuu samalle tietorakenteelle.  Tästä huonosta puolesta huolimatta tämä on ehkä parempi ratkaisu kuin lisäillä erillisiä tarkistuksia esim. `update-hoks!`-funktiossa.
Mitä mieltä olette?

schema: tarkista osaaminen saavutettu -kentän aikaväli

---

src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj

OY-3494 oli peruttu järjestelmätoimittajan bugin vuoksi.  Tästä on yli vuosi, laitetaan taas päälle.

Validate osaamisenhankkimistapa dates again

---

resources/dev/ehoks-oph.properties
resources/prod/ehoks-oph.properties
resources/test/mock/eperusteet-peruste-7534950.json
src/oph/ehoks/external/eperusteet.clj
test/oph/ehoks/external/eperusteet_test.clj

Pahoittelut ympyrässä juoksemisesta... ePerusteiden kehittäjä Olli-Pekka toteutti meidän pyynnöstä, että tuo viiteId jota tarvitaan linkkaamiseen löytyy suoraan koulutuksenOsan tiedoista (ilmeisesti tämä PR https://github.com/Opetushallitus/eperusteet/pull/1111).  Niinpä meidän ei tarvitse ladata koko perustetta (n. 212 kt) vaan riittää pelkät koulutuksenOsat (noin 55 kt).
Tätä ei voi viedä tuotantoon ennen kuin https://github.com/Opetushallitus/eperusteet/pull/1111 on tuotannossa.  Dashboardin mukaan ei oo vielä.
Koska QA-ympäristössä on jo ePerusteet josta viiteId löytyy, koodia pystyy testaamaan käsin käyttämällä ehoks-bäkkärin taustapalveluna testiopintopolun ePerusteita:
```diff
--- a/resources/dev/ehoks-oph.properties
+++ b/resources/dev/ehoks-oph.properties
@@ -32,7 +32,7 @@ …
```

ePerusteet: fetch only koulutuksenOsat when needed

---

Makefile
resources/db/oppijat/select_oppilaitos_oppijat.sql
resources/db/oppijat/select_oppilaitos_oppijat_search_count.sql
scripts/upload-hoks.sh
src/oph/ehoks/db/db_operations/db_helpers.clj
src/oph/ehoks/db/db_operations/opiskeluoikeus.clj
src/oph/ehoks/oppijaindex.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/virkailija/handler_test.clj

Muuttaa SQL-kyselyn sellaiseksi, että kaikki dynaamiset sisällöt tehdään parametreilla eikä rakennella dynaamisesti SQL-alilauseita.
https://jira.eduuni.fi/browse/EH-1467

EH-1467: korjataan tietoturva-aukko oppijat-endpointista

---

resources/db/oppijat/select_oppilaitos_oppijat.sql
resources/db/oppijat/select_oppilaitos_oppijat_search_count.sql
src/oph/ehoks/common/schema.clj
src/oph/ehoks/oppijaindex.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/virkailija/handler_test.clj

PR lisää mahdollisuuden hakea opiskeluoikeuksia HOKS-id:n perusteella ja näyttää HOKS-id hakutuloksissa.
https://jira.eduuni.fi/browse/OY-4182

Add hoks-id filter parameter and hoks-id result field in oppijat search endpoint

---

src/db/migration/V1_1687861485788__No_autogeneration_of_yksiloiva_tunniste.sql
src/oph/ehoks/hoks/hoks.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/hoks/hoks_parts/hankittavat_handler_test.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/hoks/hoks_test_utils.clj
test/oph/ehoks/oppija/handler_test.clj
test/oph/ehoks/utils.clj
test/oph/ehoks/virkailija/handler_test.clj

Instead, generate it in the API endpoint for manually creating a HOKS (POST .../api/v1/virkailija/hoksit).
Tää PR ei (vielä) estä HOKSien tallentamista ilman osaamisenhankkimistapojen yksilöiviä tunnisteita, mutta muuttaa toimintaa siten, että yksilöivät tunnisteet muodostetaan automaattisesti vain niille OHT:ille, jotka ovat uudessa, manuaalisyötetyssä HOKSissa.
https://jira.eduuni.fi/browse/EH-1472

Don't autogenerate yksiloiva tunniste in DB

---

src/oph/ehoks/heratepalvelu/herate_handler.clj
src/oph/ehoks/virkailija/external_handler.clj
src/oph/ehoks/virkailija/handler.clj
src/oph/ehoks/virkailija/system_handler.clj

Aiemmin hoksien GET-endpointissa ei voinut olla skeemaa, jottei response menisi hajalle validoinnissa vanhan väärän datan vuoksi.  Nyt kuitenkin ei-validitkin vastaukset päästetään läpi, joten skeeman voi hyvin lisätä dokumentaatioksi.  Lisätään samalla muihinkin skeemoihin, joista puuttuu.
Osa lisätyistä skeemoista on tosi epämääräisiä (turvautuu nopeasti s/Anyyn), koska varsinaisen skeeman selvittäminen tämän PR:n osana ei oo kohtuullinen työmäärä.  Voidaan tehdä niistä erillisiä PR:ia.
https://jira.eduuni.fi/browse/EH-1452

Add response schemata to most virkailija endpoints

---

src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/hoks/partial_hoks_schema.clj
src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/hoks/vipunen_schema.clj
src/oph/ehoks/schema/generator.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj
test/oph/ehoks/schema/generator_test.clj

- Tehdään mekanismi, jolla skeemoista voidaan generoida erilaisia POST-, PUT- ja PATCH-skeemoja virkailijan ja järjestelmätunnuksen endpointeille
- Luodaan infra sille, että skeemat luodaan rekursiivisesti käyttötarkoituksen perusteella yhdestä templatesta
- Päivitetään kaikki skeemat sellaisiksi, että ne käyttävät rekursiivista infraa
- Ja vihdoin: asetetaan `yksiloiva-tunniste` pakolliseksi kentäksi HOKSin skeemassa, mutta ei virkailija-endpointeissa.
- Oheisena: korjattu se, että POST-, PUT- ja PATCH-skeemoissa yhteiselle tutkinnon osalle oli unohtunut skeemaan että se voisi sisältää osaamisen hankkimistapoja tai osoittamisia.  Näille ei ollut oikeasti tukea tietokantakoodissa, joten jos HOKS oikeasti sisälsi niitä, siitä tuli 500-virheitä.  (YTO:n osa-alueet voivat sisältää näitä ja …

Parameterise HOKS schema to make yksiloiva tunniste mandatory for system transfer

---

src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj

This reverts commit c33e0c51722468b0aed04b1a4eddaccdff62eb3e.
It's because the change is wrong: the field should not be mandatory in all osaamisen hankkimistavat but only in työpaikkajaksot.

Revert "Make yksiloiva-tunniste mandatory in HOKS (not virkailija) endpoints"

---

src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/schema/generator.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj

Nyt on toteutettu tää niin kuin se oli määriteltykin eli yksilöiviä tunnisteita ei edellytetä muilta osaamisen hankkimistavoilta kuin työpaikkajaksoilta.
https://jira.eduuni.fi/browse/EH-1473

Require yksilöivä tunniste only in työpaikkajakso only for system transfer

---

README.md
src/oph/ehoks/ehoks_app.clj

Muutetaan `oph.ehoks.ehoks-app/create-app`:n palauttamat app-funktiot var:eiksi.  Var toimii ihan kuin se funktio, jonka se sisältää (delegoi funktiokutsut sisällölleen), mutta jos uusi (def) muuttaa var:n sisällön, vaihtuu myös funktio, jolle delegoidaan.  Tämä tarkoittaa, että nimiavaruuden lataaminen uudelleen näkyy välittömästi siinä, miten käynnissä oleva jetty toimii, koska uusi app-funktio päätyy var:n kautta osaksi sitä tietorakennetta, joka on annettu run-jettylle.

Create indirection in oph.ehoks.ehoks-app so that routes can be hot reloaded

---

src/oph/ehoks/hoks/hoks.clj

Vaikuttaa siltä, että koulutuksenjärjestäjät saattaa hyvinkin pidentää opiskeluoikeuden arvioitua päättymispäivää lyhyelläkin varoitusajalla ja lisätä sitten oppijalle uusia työpaikkajaksoja (koska kerran joku oli törmännyt tähän virheilmoitukseen).  Tätä varten ei käytetä indeksissä olevia alkamis- ja päättymispäivätietoja vaan haetaan aina Koskesta tuoreet tiedot (ne haetaan joka tapauksessa TUVA-tarkistusta varten).
Tämä tarkoittaa myös sitä, että indeksissä olevat pvm-tiedot ovat tällä hetkellä tarpeettomia.  En kuitenkaan ottaisi niitä välttämättä pois, koska hyvinkin voi jossain vaiheessa tulla esim. toive HOKS-listauksen rajauksesta niihin, joilla on voimassa oleva opiskeluoikeus tjsp.  Mutta voidaan myös tehdä joku siivous-PR jossa tehdään taas migraatio ettei noita juttuja …

Always fetch alkamispäivä/arvioituPäättymispäivä from Koski for oht validation

---

resources/db/hoksit/select_non_tuva_hoksit_created_between.sql
resources/db/hoksit/select_non_tuva_hoksit_finished_between.sql
src/oph/ehoks/db/db_operations/hoks.clj
src/oph/ehoks/db/queries.clj
src/oph/ehoks/external/aws_sqs.clj
src/oph/ehoks/heratepalvelu/herate_handler.clj
src/oph/ehoks/heratepalvelu/heratepalvelu.clj
src/oph/ehoks/hoks/common.clj
src/oph/ehoks/hoks/hoks.clj
src/oph/ehoks/opiskelijapalaute.clj
src/oph/ehoks/user.clj
src/oph/ehoks/virkailija/handler.clj
src/oph/ehoks/virkailija/middleware.clj
src/oph/ehoks/virkailija/system_handler.clj
test/oph/ehoks/opiskelijapalaute_test.clj
test/oph/ehoks/utils.clj

Korjattu bugi, jonka seurauksena opiskelijapalautekyselylinkkejä muodostuu TUVA-hokseille sekä TUVA-hoksien kanssa rinnakkaisille ammatillisille hokseille. Tehty refaktorointia ja lisätty testejä, joilla on yritetty yhtenäistää ja selkeyttää opiskelijapalauteen muodostuksen logikkaa.
https://jira.eduuni.fi/browse/OY-4444

OY-4444: Yhtenäistetään opiskelijapalatteiden muodostuskriteerit

---

src/oph/ehoks/hoks/hoks.clj
src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/hoks/hoks_save_test.clj

Korjattu osana OY-4444 tapahtunut regressio, jossa päättökyselyiden lähetys epäonnistuu puuttuvien tietojen vuoksi. Haetaan ajantasaisimmat tiedot kannasta ja opiskelijapalautteiden lähetyksessä näitä.
https://jira.eduuni.fi/browse/EH-1567

Fix päättökysely sending on HOKS replace

---

resources/aws-dashboard-source.json

Lisätty `ehoks-heratepalvelu` AWS Dashboardin sorsa. Nykyisestä dashboardista voi ottaa dumpin leikepöydälle valitsemalla (dashboardin ollessa avattuna) "Actions" -> "View/edit source" -> "Copy source". Vastaavasti, dashboardin saa tarvittaessa palautettua copy-pasteamalla sourcen JSON-muokkauskenttään ja painamalla "Update".
https://jira.eduuni.fi/browse/EH-1471

Add `ehoks-heratepalvelu` AWS dashboard source

---

project.clj
src/oph/ehoks/heratepalvelu/herate_handler.clj
src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/logging/audit.clj
src/oph/ehoks/virkailija/handler.clj
src/oph/ehoks/virkailija/system_handler.clj
test/oph/ehoks/virkailija/handler_test.clj

Korjataan toiminnallisuus niin, että HOKSiin tallennettavat muutokset tallentuvat auditlokiin.
Riippuu auditloggerin [muutoksesta](https://github.com/Opetushallitus/auditlogger/pull/24).
https://jira.eduuni.fi/browse/OY-4272

OY-4272: HOKSin muutokset tallentumaan auditlokiin

---

src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/hoks/hoks.clj

Tässä siis poistettu tuo otsikonmukainen lokitus `change-hoks!`-funktiosta. Lokitusta ei siis ole lisätty, toisin kuin tiketin EH-1377 kuvauksessa on ehdotettu. Tuo tiketti on muutenkin tosi vanha, ja aika paljon refaktorointia on ehtinyt tapahtua koodissa sen jälkeen. Tiketin otsikko on myös varsin lavea, tämä on tottakai moka jonka olen itse aikoinaan tehnyt. Tuon lokituksen poistaminen tuntui tässä tapauksessa sopivalta, koska käsittelemättömät poikkeukset lokitetaan joka tapauksessa `oph/ehoks/common/api.clj` poikkeuksen käsittelijässä `exception-handler`.
https://jira.eduuni.fi/browse/EH-1377
- Jos muutoksilla voi jotain rikkoessaan olla kauaskantoiset vaikutukset, kannattaa muutokset hyväksyttää useammalla …

Remove "Error caused by hoks-id ..." log print

---

src/oph/ehoks/common/api.clj
src/oph/ehoks/external/cas.clj
test/oph/ehoks/external/cas_test.clj
test/oph/ehoks/hoks/hoks_handler_test.clj

Käsitellään tilanne/tilanteet, jossa CAS palauttaa 404 haettaessa uutta Service Ticketiä. Näitä tapahtunee useimmiten sen jälkeen, kun CAS-palvelu on käynnistetty uudelleen.
https://jira.eduuni.fi/browse/EH-1518

EH-1518: Käsittele 404-virhetilanne Service Ticketiä haettaessa

---

README.md
doc/scripts.md
scripts/ask-confirmation
scripts/cas/get-service-ticket
scripts/cas/get-tgt
scripts/cas/refresh-session-cookie
scripts/check-env-vars
scripts/env/activate
scripts/koski/get-opiskeluoikeus
scripts/organisaatio/get-name
scripts/virkailija/create-hoks
scripts/virkailija/delete-hoks
scripts/virkailija/get-hoks
scripts/virkailija/get-hoks-opiskeluoikeus
scripts/virkailija/get-hoks-oppija
scripts/virkailija/replace-hoks
scripts/virkailija/update-hoks

Tämän PR:n muutokset ei vaikuta eHOKS-palvelun toiminnallisuuteen.
Lisätty muutama skripti helpottamaan testaamista ja ajoittaista selvitystyötä. Dokumentaatiota käyttöön kirjoittelin `docs/scripts.md`-tiedostoon. Skriptien toimivuus perustuu ympäristömuuttujiin, jotka asetetaan kun sourcetaan skripti `scripts/env/activate`, tyylillä:
```bash
. scripts/env/activate
```
eli toimii aika vastaavaan tapaan kuin Python-virtuaaliympäristöjen aktivointi. Em. skripti pytää käyttäjän virkailija-käyttäjätunnusta ja -salasanaa, hakee automaattisesti CAS Ticket Granting Ticketin (TGT) ja luo session cookien virkailija-rajapinnan käyttöä varten. Näin ollen, hakemiston `scripts/virkailija`-skriptit ovat valmiina käyttöä varten, TGT:n ja session cookien ollessa pitkän aikaa voimassa. Pari skriptiä …

Add few utility scripts and docs for usage

---

src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/oppijaindex_test.clj
test/oph/ehoks/utils.clj
test/oph/ehoks/virkailija/handler_test.clj

Ohitetaan osaamisen hankkimistavan päivämäärävalidointi eronneeksi katsotun (opiskeluoikeuden tila not in (valmistunut, läsnä, väliaikaisesti keskeytynyt)) oppijan HOKSille. Eli mahdollistaa tällaisen HOKSin tietojen päivittämisen ilman että työpaikkajaksojen päivämääriä pitää korjata opiskeluoikeuden uuden päättymispäivän mukaiseksi.
https://jira.eduuni.fi/browse/OY-4557

OY-4557: Ohitetaan osaamisen hankkimistavan päivämäärävalidointi eronneeksi katsotun oppijan HOKSille

---

src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/hoks/vipunen_schema.clj
src/oph/ehoks/schema/oid.clj
test/oph/ehoks/db/opiskelijan_yhteystiedot_test.clj
test/oph/ehoks/db/tyopaikkaohjaajan_yhteystiedot_test.clj
test/oph/ehoks/external/oppijanumerorekisteri_test.clj
test/oph/ehoks/heratepalvelu/herate_handler_test.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/hoks/hoks_parts/hankittavat_handler_test.clj
test/oph/ehoks/hoks/hoks_parts/parts_test_data.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/hoks/hoks_test_utils.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj
test/oph/ehoks/hoks/test_data.clj
test/oph/ehoks/opiskelijapalaute_test.clj
test/oph/ehoks/oppija/handler_test.clj
test/oph/ehoks/oppija/oppija_external_test.clj
test/oph/ehoks/oppija/share_handler_test.clj
test/oph/ehoks/oppijaindex_test.clj
test/oph/ehoks/schema/oid_test.clj
test/oph/ehoks/user_test.clj
test/oph/ehoks/utils.clj
test/oph/ehoks/virkailija/auth_test.clj
test/oph/ehoks/virkailija/cas_handler_test.clj
test/oph/ehoks/virkailija/handler_test.clj
test/oph/ehoks/virkailija/virkailija_external_test.clj
test/oph/ehoks/virkailija/virkailija_test_utils.clj

Osana OY-4553 tikettiä on tarkoitus tehdä työkalu OPH-pääkäyttäjille oppijanumeroiden manuaaliseen päivittämiseen "Ylläpito"-välilehdelle. Koska päivityksiä on määrä tehdä käsin (käytännössä luultavasti siis copy-pastetaan oppija-oideja Ylläpito-välilehden kenttiin), on syytä tiukentaa OID:ien validointia, jotta vältetään vahingossa tehdyt virheelliset päivitykset. OID:ien validointi on tottakai hyödyllistä olla olemassa muutenkin: Vaikka järjestelmien välillä pallotellaankin suurimmaksi osin automaattisesti generoituja OID:eja, voi olla että joissain tapauksissa näitä naputellaan myös lähdejärjestelmiin käsipelin.
[OID-generaattori](https://github.com/Opetushallitus/java-utils/blob/master/oid-generator/src/main/java/fi/vm/sade/oidgenerator/OIDGenerator.java) lisää OID:ien loppuosan …

More strict validation for different OID classes

---

src/oph/ehoks/oppijaindex.clj
test/oph/ehoks/oppijaindex_test.clj

- don't treat name changes and slave updates as alternatives, instead, do both as needed
- always remove old duplicate oids
- add new ONR data the same way as oppijaindex is usually updated
https://jira.eduuni.fi/browse/OY-4523

More robust ONR update handling

---

src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/hoks/hoks.clj
test/oph/ehoks/hoks/hoks_handler_test.clj

Because osa-aikaisuustieto is mandatory nowadays, this code does not have much point.
https://jira.eduuni.fi/browse/EH-1598

Remove notification code for missing osa-aikaisuustieto (EH-1598)

---

.github/workflows/build.yml
src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/hoks/hoks_test_utils.clj
test/oph/ehoks/virkailija/handler_test.clj

Salli shallow delete myös ilman organisaatio-oidia
https://jira.eduuni.fi/browse/OY-4647

OY-4647: Salli shallow delete myös ilman organisaatio-oidia

---

src/oph/ehoks/validation/handler.clj

Validaatio-API:sta puuttui `wrap-opiskeluoikeus` middleware, jolloin opiskeluoikeudesta riippuvat skeematarkistukset epäonnistuvat. Lisätty kyseinen middleware.

Fix validation API by adding `wrap-opiskeluoikeus` middleware

---

resources/aws-dashboard-source.json

AWS Dashboard-sorsan päivittäminen. Application ELB:n HTTP status-koodeja monitoroivasta graafista puuttui eu-west-1a Availavility Zonen 2XX/4XX/5XX-statuskoodimetriikat. Näitä ei oltu aiemmin lisätty, kun eivät olleet aiemmalla lisäyskerralla saatavilla.

Update AWS dashboard source

---

src/oph/ehoks/common/schema.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/virkailija/handler_test.clj

Trimmaa json bodystä kaikki tekstimuotoiset kentät. Tarve oli trimmata vain työpaikan nimi, mutta tällä trimmautuu kaikki. Ei liene huono asia?
https://jira.eduuni.fi/browse/EH-1601

EH-1601: Trimmaa json bodystä kaikki tekstimuotoiset kentät

---

src/oph/ehoks/common/api.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj
test/oph/ehoks/oppija/share_handler_test.clj

`:schema` pois bad requestin vastauksen bodystä.
https://jira.eduuni.fi/browse/EH-1536

EH-1536: schema pois bad requesteista

---

src/oph/ehoks/logging/audit.clj
test/oph/ehoks/logging/audit_test.clj

Audit-lokien `changes`-muutoslistassa on suhteettoman paljon `:module-id` päivityksiä. Tässä pikainen korjaus, jolla rajataan muutoslistauksesta pois `:module-id` avaimeen päättyvät polut.

audit logging: exclude paths with `:module-id` from changes list

---

src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/virkailija/handler_test.clj
test/oph/ehoks/virkailija/virkailija_test_utils.clj

Korjataan muiden oppilaitosten HOKSien näyttäminen virkailijalle niin, että virkailija saa nähdä muiden oppilaitosten HOKSit niin kauan kuin hänen edustamissaan oppilaitoksissaan on (yksikin) HOKS voimassa kyseiselle oppijalle.
https://jira.eduuni.fi/browse/EH-1649

EH-1649: Muiden oppilaitosten HOKSien näyttäminen virkailijalle

---

src/oph/ehoks/db/db_operations/hoks.clj
src/oph/ehoks/db/queries.clj
src/oph/ehoks/heratepalvelu/herate_handler.clj

Otetaan takaisin käyttöön toiminnallisuus, joka etsii HOKSin tietokannasta vanhoja HOKSeja / työpaikkajaksoja ja poistaa niistä yhteystietoja.
https://jira.eduuni.fi/browse/EH-1514

EH-1451: re-enable deleting contact info from over 3 month old HOKSes/OHTs

---

resources/dev/ehoks-oph.properties
resources/prod/ehoks-oph.properties
src/oph/ehoks/external/oppijanumerorekisteri.clj
src/oph/ehoks/hoks.clj
src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj
test/oph/ehoks/virkailija/handler_test.clj

Mahdollistetaan HOKSiin tallennetun oppija-oidin vaihtaminen validoimalla se oppijanumerorekisteriä vasten.
https://jira.eduuni.fi/browse/EH-1560

EH-1560: oppija-oidin vaihtamisen validointi

---

resources/db/hoksit/select_oht_by_tutkinto_between.sql
src/oph/ehoks/db/postgresql/common.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/virkailija/handler_test.clj

Oppilaitos ei saa avattua raportteja. Muutetaan raporttien palauttama tietorakenne sellaiseksi, jota käyttöliittymä odottaa.
https://jira.eduuni.fi/browse/EH-1682

EH-1682: Korjaa raporttirajapintojen tietorakenne

---

.github/workflows/build.yml
.gitignore
Makefile
README.md
oph-configuration/default.edn
project.clj
resources/dev/demo-data/anonymised-example-1.json
resources/dev/demo-data/anonymised-example-2.json
resources/dev/src/oph/ehoks/mocked_routes/mock_koski_routes.clj
src/db/migration/V1_1721307219687__AMIS_palaute_sync_view.sql
src/oph/ehoks/db/db_operations/db_helpers.clj
src/oph/ehoks/db/dynamodb.clj
src/oph/ehoks/db/sql/opiskelijapalaute.sql
src/oph/ehoks/schema.clj
src/oph/ehoks/virkailija/handler.clj
test/oph/ehoks/db/dynamodb_test.clj
test/oph/ehoks/external/koski_test.clj

Tämän PR:n pointtina on ennen kaikkea uusi nimiavaruus `oph.ehoks.db.dynamodb`, jossa on käsittelijät, joilla voi synkata tietoja palaute-backendin tietokannasta herätepalvelun dynamodb-tauluihin.
https://jira.eduuni.fi/browse/EH-1584

EH-1584: Writing herätteet directly to DynamoDB

---

src/oph/ehoks/common/api.clj
src/oph/ehoks/external/cas.clj
src/oph/ehoks/external/koodisto.clj
src/oph/ehoks/external/koski.clj
src/oph/ehoks/external/oppijanumerorekisteri.clj
src/oph/ehoks/external/organisaatio.clj
src/oph/ehoks/hoks.clj
src/oph/ehoks/oppijaindex.clj
test/oph/ehoks/external/cas_test.clj
test/oph/ehoks/external/koski_test.clj
test/oph/ehoks/hoks/invalid_hoks_handler_test.clj
test/oph/ehoks/oppijaindex_test.clj
test/oph/ehoks/virkailija/handler_test.clj

Selvittelen https://jira.eduuni.fi/browse/EH-1703 ongelmaa. Huomasin, että AMISTimedOperationsHandler-lambdan triggeröimässä opiskelijapalauteherätteiden uudelleenlähetyksessä `palaute/opiskelija.clj` opiskeluoikeuden hakeminen Koskesta epäonnistuu syystä X, ja tämä mitä varmimmin saa koko lambdan ajon epäonnistumaan (molempien ongelmien alkamisajankohta, 12.8. klo 8:30, täsmää).
Tein tämän pienen muutoksen tukemaan ongelman selvittelyä, mutta auttaa tottakai vastaisuudessakin vastaavanlaisissa tilanteissa. Muutoksen kautta saisi lokeille poikkeuksen viestin lisäksi näkymään `ex-data`-tiedot poikkeuksen ollessa tyyppiä `ExceptionInfo`.
https://jira.eduuni.fi/browse/EH-1703
- Jos muutoksilla voi jotain rikkoessaan olla …

More info to log messages

---

src/oph/ehoks/palaute/tyoelama.clj

Tämän muutoksen pointti on huolehtia, ettei EH-1585:n koodi muuttele muuta kuin palautetauluja, ennen kuin se on oikeasti käytössä.

EH-1585: Prevent updating tep-kasitelty if no handling was actually done

---

src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/middleware.clj
test/oph/ehoks/hoks/hoks_save_test.clj

The failures usually realise in API endpoints that return and validate HOKSes.  This is because the current opiskeluoikeus is usually fetched only in endpoints that need to validate new data.  The failing validations cause a lot of false alarms in logs, and are so numerous that they actually make it harder to use the logs.
https://jira.eduuni.fi/browse/EH-1689

EH-1689: fix validators failing when there is no current opiskeluoikeus

---

src/oph/ehoks/hoks/osaamisen_hankkimistapa.clj
src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/tyoelama.clj
src/oph/ehoks/utils/date.clj
test/oph/ehoks/palaute/opiskelija_test.clj
test/oph/ehoks/palaute/tyoelama_test.clj

Tässä PR:ssä on osa niistä muutoksista, joilla korjataan opiskelija- ja työelämäpalautteen luomislogiikka toimimaan keskenään samalla tavalla.  Niiden herätepalvelu-koodissa on paljon tuplana kirjoitettua logiikkaa, minkä vuoksi myös yhdestä tai toisesta on helposti unohtunut jokin sääntö.  Lisäksi skeematarkistuksissa näytti olevan päällekkäisyyttä palautetarkistusten kanssa, tässä ainakin muutama eliminoitu.
- https://jira.eduuni.fi/browse/EH-1704
- https://jira.eduuni.fi/browse/EH-1583

EH-1704: fixes to tyoelamapalaute logic

---

Makefile
resources/db/heratepalvelu/select_hato_tyoelamajaksot_active_between.sql
resources/db/heratepalvelu/select_hpto_tyoelamajaksot_active_between.sql
resources/db/heratepalvelu/select_hyto_tyoelamajaksot_active_between.sql

EH-1699 muutosten myötä, Herätepalvelussa aletaan käyttämään jaksojen yksilöintiin (hoks_id, yksiloiva_tunniste)-kombinaatiota. Tämän mahdollistamiseksi, sekä hoks_id että yksiloiva_tunniste täytyy sisällyttää mukaan `select_%_tyopaikkajaksot_active_between.sql`-kyselyihin.
https://jira.eduuni.fi/browse/EH-1699

EH-1699: Add `hoks_id` and `yksiloiva_tunniste` to `select_%_tyopaikkajaksot_active_between.sql` queries

---

src/oph/ehoks/hoks/schema.clj
src/oph/ehoks/opiskeluoikeus.clj
src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/tyoelama.clj
test/oph/ehoks/palaute/tyoelama_test.clj
test/oph/ehoks/palaute_test.clj

Some more fixes from EH-1704:
- fix in-terminal-state? to be according to its specification
- remove discrepancies between amis and tep palaute creation, so that both have all fields filled in (with the same logic).
https://jira.eduuni.fi/browse/EH-1704
https://jira.eduuni.fi/browse/EH-1443
https://jira.eduuni.fi/browse/OY-4433

EH-1704: fix palaute logic (vol 2)

---

resources/dev/demo-data/hoksit.json
src/oph/ehoks/db/sql/palaute.sql
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/tyoelama.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/palaute/opiskelija_test.clj
test/oph/ehoks/palaute/tyoelama_test.clj
test/oph/ehoks/test_utils.clj
test/oph/ehoks/virkailija/handler_test.clj

Luodaan testit seuraaville asioille:
- palautteet ja palautetapahtumat muodostuvat oikein HOKSin tallennuksen yhteydessä (osittain päällekkäisiä palautetestien kanssa)
- HOKSin päivittäminen palautteenkeruun kannalta olennaisista kohdista myös muuttaa palautteiden tietoja
- HOKSin päivitykset eivät tuota lisäpalauterivejä vaan päivittävät vanhoja
- Jo lähetettyjä palautteita ei päivitetä, vaan ne joko estävät palautteen keruun uusilla tiedoilla kokonaan, tai aiheuttavat uuden palautteenkeruun (mikäli vanha ja uusi amispalaute ovat eri rahoituskausilla) 
- Lisäksi PR:ssä on korjattu yksi bugi, joka esti jo luotuja työelämäpalautteita päivittymästä oikein.
https://jira.eduuni.fi/browse/EH-1716
- Jos muutoksilla voi jotain …

EH-1716: add tests for palaute state changes in upserts

---

.github/workflows/create-lampi-export-runner-image.yml
scripts/lampi-export/Dockerfile
scripts/lampi-export/lampi-export.sh

Lampi-exportterin imagen luonti. Vaatii [cloud-basen PR:n](https://github.com/Opetushallitus/cloud-base/pull/291) toimiakseen. Vaatii myös [tietokantanäkymät](https://github.com/Opetushallitus/ehoks/pull/645) toimiakseen.
https://jira.eduuni.fi/browse/OY-4686

OY-4685 & OY-4686: Lampi-exportterin imagen luonti

---

src/db/migration/V1_1731917685939__remove_trigram_index.sql

This is cleaning up after EH-974 and its rollback in c8f7fce595c.
https://jira.eduuni.fi/browse/EH-1751

EH-1751: remove unused trigram index on oppijat.nimi

---

src/db/migration/V1_1733403708934__extend_tapahtumatyypit.sql
src/db/migration/V1_1733765792887__add_lahetystila_to_tep_heratepalvelu_view.sql
src/db/migration/V1_1733775117387__add_lahetystila_to_amis_heratepalvelu_view.sql
src/oph/ehoks/db/dynamodb.clj
src/oph/ehoks/db/sql/palaute.sql
src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/tyoelama.clj
test/oph/ehoks/db/dynamodb_test.clj
test/oph/ehoks/palaute/opiskelija_test.clj
test/oph/ehoks/palaute/tyoelama_test.clj

When syncing palaute to heratepalvelu, create lahetystila/kasittelytila fields that heratepalvelu uses to find heratteet to process forth.
https://jira.eduuni.fi/browse/EH-1711

EH-1711: add missing fields needed by heratepalvelu

---

src/db/migration/V1_1735630752497__Exclude_temp_tables.sql

Rajaa temp-taulut pois raportoinnista
OY-4608

OY-4608: Rajaa temp-taulut pois raportoinnista

---

scripts/lampi-export/Dockerfile
scripts/lampi-export/lampi-export.sh
scripts/lampi-export/send-error-message.sh

Tee assume role ennen jokaista siirtoa, jotta väliaikainen access key ei ehdi vanhentua.
OY-4608

OY-4608: Muutoksia Lampi-skriptiin

---

resources/db/hoksit/select_non_tuva_hoksit_created_between.sql
resources/db/hoksit/select_non_tuva_hoksit_started_between.sql
src/oph/ehoks/db/db_operations/hoks.clj
src/oph/ehoks/db/queries.clj
src/oph/ehoks/heratepalvelu.clj
src/oph/ehoks/heratepalvelu/herate_handler.clj
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/tyoelama.clj
src/oph/ehoks/virkailija/system_handler.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/palaute/opiskelija_test.clj

After these changes, the `resend-aloitusherate` and `resend-paattoherate` APIs (there are two of each) do the following things for the HOKSen created between the given dates:
- update palaute status and info in DB, for instance if opiskeluoikeus info has changed in between
- resend the SQS message to heratepalvelu.
As a sidenote, using the creation date is probably not correct; it will skip HOKSen that were just updated in the last two weeks (or whatever the given dates are).
https://jira.eduuni.fi/browse/EH-1757

EH-1757: Fix resend functionality

---

src/db/migration/V1_1738230258420__add_missing_palautteet_indices.sql

EH-1757:n asennuksen yhteydessä (#665) tuli ilmi, että kyselyt ovat todella hitaita.  Testatessa ilmeni, että se johtuu hitaasta FOREIGN KEY -triggerien suorituksesta, koska tietokannasta puuttuvat indeksit, joita ne tarvitsisivat.
Tämä PR perustaa kyseiset indeksit.  `master`-haaraan on tosin jo mergetty migraatio, joka tarvitsisi näitä indeksejä.  Ratkaisu on se, että ajetaan molempien SQL-komennot etukäteen käsin (ne ovat idempotentteja).  Migraatiot jäävät dokumentaatioksi, että nämä operaatiot on tehty.
https://jira.eduuni.fi/browse/EH-1771

EH-1771: create missing indices on reference columns

---

src/oph/ehoks/hoks/schema.clj
test/oph/ehoks/external/koski_test.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/test_utils.clj

Varmistetaan osana skeematarkituksia, että opiskeluoikeuden tyyppi on joko `ammatillinenkoulutus` tai `tuva`.
https://jira.eduuni.fi/browse/EH-1748

Validate opiskeluoikeus type

---

src/db/migration/V1_1740751280614__Remove_unused_palaute_views.sql
src/oph/ehoks/db/dynamodb.clj
src/oph/ehoks/db/sql/palaute.sql
src/oph/ehoks/external/arvo.clj
src/oph/ehoks/heratepalvelu.clj
src/oph/ehoks/hoks/osaamisen_hankkimistapa.clj
src/oph/ehoks/opiskeluoikeus/suoritus.clj
src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/handler.clj
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/scheduler.clj
src/oph/ehoks/palaute/tyoelama.clj
src/oph/ehoks/palaute/tyoelama/nippu.clj
src/oph/ehoks/palaute/vastaajatunnus.clj
src/oph/ehoks/utils.clj
test/oph/ehoks/db/dynamodb_test.clj
test/oph/ehoks/hoks/hoks_test_utils.clj
test/oph/ehoks/opiskeluoikeus/suoritus_test.clj
test/oph/ehoks/palaute/handler_test.clj
test/oph/ehoks/palaute/opiskelija_test.clj
test/oph/ehoks/palaute/tyoelama/nippu_test.clj
test/oph/ehoks/palaute/tyoelama_test.clj
test/oph/ehoks/palaute_test.clj

Tämä PR on osa EH-1732:sta: siinä toteutetaan se osa, että herätepäivänä haetaan HOKSin ja opiskeluoikeuden tiedot ja tarkistetaan niiden perusteella, kuuluuko palaute kohderyhmään.  Samalla siinä toteutetaan EH-1737:a sillä jos EH-1737:n tekisi ensin, joutuisi refaktoroimaan koodia joka tulee muuttumaan tyystin, mutta jos EH-1732:n tekee ensin, joutuu tekemään käytännössä samat muutokset kahteen eri koodiin (AMIS- ja TEP-vastaajatunnusten luontiin).
https://jira.eduuni.fi/browse/EH-1732
https://jira.eduuni.fi/browse/EH-1737

EH-1732: checking kohderyhmä at herätepvm

---

src/oph/ehoks/db/dynamodb.clj
src/oph/ehoks/external/arvo.clj
src/oph/ehoks/heratepalvelu.clj
src/oph/ehoks/palaute/tyoelama.clj

#669 broke heratepalvelu-responsibilities.  Fix that and also unify the way to handle Arvo calls not made.

EH-1732: handle the *-responsibilities config correctly

---

src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/tyoelama.clj
test/oph/ehoks/palaute/opiskelija_test.clj

This is the change agreed on in the team about handling palautteet based on handling date (käsittelypäivä) information.  Because opiskeluoikeus data is external and can change without notification to eHOKS, we put palautteet in :odottaa-kasittelya state when the verdict is based on opiskeluoikeus fields.  This causes them to be handled on their heratepvm (or later), using the information in Koski on that date.  This means that the opiskeluoikeus information can be corrected during this time.
When heratepvm has gone, the only way to retrigger palaute handling is to resave the HOKS.  This usually makes sense because the only way to change the heratepvm is also to resave.
- Jos muutoksilla voi jotain rikkoessaan olla …

EH-1732: if initial-state is based on opiskeluoikeus, handle later again

---

src/oph/ehoks/external/arvo.clj
src/oph/ehoks/palaute/scheduler.clj
src/oph/ehoks/palaute/vastaajatunnus.clj

-    muodostetaan pseudotunnukset uniikkeita, mutta esim. dummy-etuliitteellä.
-    ei yritetä poistaa pseudotunnuksia Arvosta.
-    käsitellään poikkeukset myös handle-exceptionissa
-    suojataan daily-actions! poikkeuskäsittelijällä, ettei se kaada scheduleria
-    (Tehdään lokiviesti daily-actions!in alkuun)
https://jira.eduuni.fi/browse/EH-1798
TODO: PR:iin liittyvä Jira-tiketti (tunniste ja linkki)

EH-1798: fix exception and dummies in vastaajatunnus handling

---

src/oph/ehoks/external/koski.clj
src/oph/ehoks/palaute/vastaajatunnus.clj
src/oph/ehoks/utils.clj
test/oph/ehoks/palaute/tyoelama_test.clj

Multiple palautteet may share the same HOKS they come from.  Because fetching the HOKS from DB is quite a heavy operation, when handling palautteet that have reached their heratepvm, cache the last HOKS in case the next palaute is for the same HOKS.

EH-1798: don't reconstruct HOKSen from DB for each palaute

---

src/oph/ehoks/palaute/opiskelija.clj

Huomasin opiskelijapalautteen lokituksessa pikkuhäikän, tässä korjaus.

Fix `kysely-type` in opiskelijapalaute logging

---

src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/tyoelama.clj

... because saving the same HOKS twice very quickly may miss the already existing palaute from each other, potentially causing two palaute records to be formed for the same palaute.

EH-1706: run palaute creation in serializable transactions

---

src/oph/ehoks/palaute.clj
test/oph/ehoks/palaute_test.clj

Tällainen tuli vastaan, kun tutkin lokeja.  Näyttäisi toimivan nykyiselläänkin, mutta tässä versiossa ei kutsuta turhaan organisaatiopalvelua ja lisätään erillinen varoitus siitä, että funktiota on kutsuttu `nil`:llä.

Handle nil opiskeluoikeus properly in koulutustoimija

---

resources/db/hoksit/select_kyselylinkit_by_oppija_oid.sql
resources/dev/demo-data/jaksotunnus-schema.json
resources/dev/src/oph/ehoks/dev_server.clj
src/db/migration/V1_1742311147193__Mark_old_palautteet_as_deleted.sql
src/db/migration/V1_1742370906697__Add_palautetila_heratepalvelussa.sql
src/oph/ehoks/db/dynamodb.clj
src/oph/ehoks/db/sql.clj
src/oph/ehoks/db/sql/palaute.sql
src/oph/ehoks/db/sql/palautetapahtuma.sql
src/oph/ehoks/heratepalvelu.clj
src/oph/ehoks/hoks/handler.clj
src/oph/ehoks/main.clj
src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/initiation.clj
src/oph/ehoks/palaute/opiskelija.clj
src/oph/ehoks/palaute/scheduler.clj
src/oph/ehoks/palaute/tyoelama.clj
test/oph/ehoks/db/dynamodb_test.clj
test/oph/ehoks/hoks/hoks_handler_test.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/palaute/handler_test.clj
test/oph/ehoks/palaute/initiation_test.clj
test/oph/ehoks/palaute/opiskelija_test.clj
test/oph/ehoks/palaute/tyoelama/nippu_test.clj
test/oph/ehoks/palaute/tyoelama_test.clj
test/oph/ehoks/palaute_test.clj
test/oph/ehoks/test_utils.clj

Palaute-backend ei saa tehdä Arvo-kutsuja niille palautteille, joille herätepalvelu voi tehdä Arvo-kutsuja (jottei samalle palautteelle muodosteta kahta vastaajatunnusta).  Tämä PR estää niiden palautteiden käsittelyn, jotka ovat jo herätepalvelussa.
https://jira.eduuni.fi/browse/EH-1804

EH-1804: prevent handling of palautteet already in Herätepalvelu

---

src/db/migration/V1_1745394959342__Add_palaute_initiated_at_column_to_hoksit.sql
src/oph/ehoks/db/db_operations/db_helpers.clj
src/oph/ehoks/db/db_operations/hoks.clj
src/oph/ehoks/db/sql/palaute.sql
src/oph/ehoks/palaute/initiation.clj
test/oph/ehoks/hoks/hoks_save_test.clj
test/oph/ehoks/palaute/initiation_test.clj

Lisätään `hoksit`-tauluun `palaute_handled_at` kenttä. Uudelleenkäsittelyn yhteydessä tarkastetaan, onko kyseiseen kenttään asetettu timestamp, ja jos on, ei käsitellä palautteita uudelleen hoksille.
https://jira.eduuni.fi/browse/EH-1812

Add `palaute_handled_at` column to `hoksit` table

---

src/oph/ehoks/palaute/scheduler.clj

Kasvatetaan batch size 500 -> 2500 jotta hoksien palautteet tulee käsiteltyä nopeammin.

Increase `reinit-palautteet-for-uninitiated-hokses!` batch size

---

src/oph/ehoks/hoks/handler.clj

Viime yritys (#703) rikkoi audit-lokituksen siinä mielessä, että vanha ja uusi kyselylinkkidata eivät ole enää samassa muodossa ja siksi diff niiden välillä ei toimi.
https://jira.eduuni.fi/browse/EH-1816

EH-1816: fix kyselylinkki found check in a way that doesn't break audit logging

---

src/db/migration/V1_1748793635101__Reset_palautteet_with_dummy_tunnus.sql
src/oph/ehoks/palaute.clj
src/oph/ehoks/palaute/tyoelama.clj
src/oph/ehoks/palaute/vastaajatunnus.clj
test/oph/ehoks/palaute/opiskelija_test.clj
test/oph/ehoks/palaute/tyoelama_test.clj

Palautetaan dummy-tunnukselliset palautteet takaisin `odottaa_kasittelya` tilaan. Varmistetaan, että Herätepalvelussa oleville palautteille ei muodosteta uutta tunnusta/kyselylinkkiä, jos syystä taikka toisesta tällainen on jo Herätepalvelussa.
https://jira.eduuni.fi/browse/EH-1805

EH-1805: Asetetaan dummy-tunnukselliset palautteet takaisin `odottaa_kasittelya` tilaan

---

src/oph/ehoks/palaute/scheduler.clj

Koulutuksenjärjestäjät haluavat että opiskelijat saavat palautelinkin nopeasti kun ensikertainen hyväksyminen on kirjattu.  Korjataan aluksi siihen, että kerran tunnissa käsitellään palautteet.  Myöhemmin voidaan harkita reaaliaikaisuutta.
https://jira.eduuni.fi/browse/EH-1846

EH-1846: process palaute more often (once an hour)
