resources/dev/src/oph/ehoks/dev_server.clj, src/oph/ehoks/main.clj
Tuki asynkronisille routeille.
=> Eh 93 dev async

config/default.edn, src/oph/ehoks/handler.clj, src/oph/ehoks/misc/handler.clj, src/oph/ehoks/misc/schema.clj, src/oph/ehoks/schema.clj, test/oph/ehoks/misc/handler_test.clj
Ympäristön tietojen hakemiseen oma endpoint.
Lähinnä alkuun Opintopolku-login-tiedon hakeminen.
=> Eh 98 environment

config/default.edn, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/mock_routes.clj, src/oph/ehoks/auth/handler.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/schema.clj
=> Eh 102 fix logout

src/oph/ehoks/external/eperusteet.clj
Korjataan ePerusteet urlin path
=> Remove info path

project.clj
Cloveragen lisäys projektiin.
Lisäksi riippuvuuksien päivitys.
=> Eh 104 cloverage and gals

src/oph/ehoks/lokalisointi/handler.clj
Jees eli muutettiin vaan tuo lokalisointien haku asynkroniseksi bäkkärillä lisäämällä yksinkertainen async/go-blokki. Samalla vähän viilauksia muotoiluun.
=> Eh 86 make localization async

config/default.edn, project.clj, resources/dev/dev-routes/rest_codeelement_ravintolakokinatjarjestys__4_2.json, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/mock_routes.clj, resources/test/mock/koodisto-value.json, src/oph/ehoks/external/handler.clj, src/oph/ehoks/external/koodisto.clj, src/oph/ehoks/external/schema.clj, src/oph/ehoks/schema.clj, test/oph/ehoks/external/koodisto_test.clj
=> Eh 111 koodisto integration

config/default.edn, src/oph/ehoks/external/connection.clj, src/oph/ehoks/external/eperusteet.clj, src/oph/ehoks/external/handler.clj, src/oph/ehoks/external/koodisto.clj, src/oph/ehoks/external/lokalisointi.clj, src/oph/ehoks/external/oppijanumerorekisteri.clj, test/oph/ehoks/external/connection_test.clj, test/oph/ehoks/external/oppijanumerorekisteri_test.clj
Caller Id jokaiseen kutsuun.
Samalla rajapinnan siistiminen ja yhtenäistäminen.
=> Eh 119 caller

src/oph/ehoks/handler.clj, src/oph/ehoks/roles.clj
Tuki reittikohtaisille rooleille
=> Eh 89 roles

config/default.edn, resources/dev/dev-routes/koski_api_oppija_1.2.246.562.24.44651722625.json, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/mock_routes.clj, src/oph/ehoks/external/handler.clj, src/oph/ehoks/external/koski.clj, src/oph/ehoks/external/schema.clj, src/oph/ehoks/schema.clj, test/oph/ehoks/external/koski_test.clj
=> Eh 72 koski integration

config/default.edn, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/mock_routes.clj, src/oph/ehoks/external/koodisto.clj, src/oph/ehoks/external/schema.clj, src/oph/ehoks/external/utils.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/schema.clj
Poikkeusten js virhetilanteiden hallinta paremmaksi
=> Eh 101 error handling

README.md, project.clj, src/oph/ehoks/external/connection.clj, src/oph/ehoks/external/eperusteet.clj, src/oph/ehoks/external/koodisto.clj, src/oph/ehoks/external/koski.clj, src/oph/ehoks/external/lokalisointi.clj, src/oph/ehoks/external/oppijanumerorekisteri.clj, test/oph/ehoks/external/connection_test.clj
Logiin menevien parametrien ja pathin putsaus.
Pikkuisen jotain muutakin mukana.
=> Eh 150 clean log params

doc/hoks.md, src/oph/ehoks/hoks/schema.clj
=> Eh 147 hoks model update

doc/hoks.md, src/oph/ehoks/auth/handler.clj, src/oph/ehoks/external/handler.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/healthcheck/handler.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/lokalisointi/handler.clj, src/oph/ehoks/misc/handler.clj, src/oph/ehoks/schema_tools.clj, test/oph/ehoks/schema_tools_test.clj
Rajapintojen pilkkomista pienempiin osa-alueisiin. Tätä varten funktiot, joilla voi schemoja muokata metodeille sopiviksi (GET, POST, PUT, PATCH).
=> Eh 154 apis

doc/hoks.md, help/hoks-restful.md, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj
Puuttuva paikallinen tutkinnon osa
=> Eh 158 ppto

doc/hoks.md, resources/dev/src/oph/ehoks/hoks_doc.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj
Kuten slackissa käyty läpi, tässäpä olisi nämä OlemassaOlevaOsaaminen - muutokset.
=> Eh 167 olemassa oleva osaaminen

config/default.edn, resources/dev/src/oph/ehoks/mock_routes.clj, src/oph/ehoks/common/schema.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/schema.clj, src/oph/ehoks/tyopaikan_toimija/handler.clj
=> Eh 145 tyopaikan toimija

doc/hoks.md, resources/dev/src/oph/ehoks/hoks_doc.clj
=> Eh 176 177 gendoc improvements

src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/utils.clj
=> Eh 156 158 tests

src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj
Added post, put, patch and get to puuttuvat-yhteisen-tutkinnon-osat as well ass tests for the handler.
=> Eh 157 api for puuttuvat yhteisen tutkinnon osat

doc/hoks.md, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj
Elikäs, luotu hoks/handler.clj:hin get, post, put ja patch, sekä niille tarvittavat schemaan. Lisäksi generoitu uusi hoks.md.
=> Eh 159 opiskeluvalmiuksia tukevat opinnot

project.clj, src/oph/ehoks/db/memory.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/utils.clj
Yksinkertainen muistiin tiedon tallennus testailuja varten HOKSin osalta.
Mukana Clojuren ja depsujen päivitys.
=> Eh 114 hoks store

doc/hoks.md, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj
Lisäilty siis (tämänhetkisen) tietomallin mukainen olemassa-oleva-osaaminen apin endpoint ja skeema sekä myöskin testit. Generoitu myös uusi hoks.md
=> Eh 160 olemassa oleva osaaminen

README.md, resources/dev/demo-data/hoksit.json, resources/dev/demo-data/oppijat.json, resources/dev/src/oph/ehoks/dev_server.clj, src/oph/ehoks/db/memory.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj
Demodatan tuonti sovelluksen käynnistyessä
=> Eh 195 demo data import

src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/schema_tools.clj
Scheman muokkaus.
Katso: https://jira.csc.fi/browse/EH-185
=> Eh 186 modify schemas

project.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/resources.clj
Kevyt staattisten tiedostojen tarjoiluun service json-vieweriä varten
=> Eh 201 json viewer backend

resources/dev/demo-data/hoksit.json, resources/test/src/oph/ehoks/session_store.clj, src/oph/ehoks/db/memory.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/oppija/handler.clj, test/oph/ehoks/oppija/handler_test.clj, test/oph/ehoks/utils.clj
Hoksi tulemaan muistista istunnon käyttäjälle
=> Eh 200 oppija and memory db

json-schema-viewer/Gruntfile.js, json-schema-viewer/package-lock.json, json-schema-viewer/package.json
and removed unnecessary dependencies
=> EH-197: Upgraded vulnerable json-schema-viewer dependencies

src/oph/ehoks/schema_tools.clj, test/oph/ehoks/schema_tools_test.clj
=> Add support for modify

src/oph/ehoks/handler.clj, src/oph/ehoks/validation/handler.clj
=> Add data validation handler

resources/dev/demo-data/hoksit.json, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/hoks_json_converter.clj, src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/oppija/handler.clj, test/oph/ehoks/oppija/handler_test.clj
YTO Koodisto-koodi-rikastus.
Demodataan lisätty tähän liittyvää dataa.
=> Eh 239 yto enrich

src/oph/ehoks/external/handler.clj, src/oph/ehoks/handler.clj
Reverts Opetushallitus/ehoks#81
=> Revert "Eh 253 hide external apis"

src/oph/ehoks/db/hoks.clj, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/hoks_test.clj
Olemassa olevat paikalliset tutkinnon osat tietokantaan
=> Add olemassa olevat paikalliset tutkinnon osat

resources/db/olemassa-olevat-yhteiset-tutkinnon-osat/select_hankitun_osaamisen_naytot.sql, resources/db/olemassa-olevat-yhteiset-tutkinnon-osat/select_koulutuksen_jarjestaja_arvioijat.sql, resources/db/olemassa-olevat-yhteiset-tutkinnon-osat/select_osa_alue_hankitun_osaamisen_naytot.sql, resources/db/olemassa-olevat-yhteiset-tutkinnon-osat/select_osa_alueet.sql, src/oph/ehoks/db/hoks.clj, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/hoks_test.clj
Olemassa olevien yhteisten tutkinnon osien tallennus ja luku
=> Eh 276 ooyto db

resources/db/puuttuvat-ammatilliset-tutkinnon-osat/select_by_hoks_id.sql, resources/db/puuttuvat-ammatilliset-tutkinnon-osat/select_hankitun_osaamisen_naytot.sql, resources/db/puuttuvat-ammatilliset-tutkinnon-osat/select_osaamisen_hankkimistavat.sql, src/oph/ehoks/db/hoks.clj, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/hoks_test.clj
Puuttuvat ammatilliset tutkinnon osat (puutuva ammatillinen osaaminen) tietokantaan
=> Eh 277 pao db

resources/db/opiskeluvalmiuksia-tukevat-opinnot/select_by_hoks_id.sql, src/oph/ehoks/db/hoks.clj, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/hoks_test.clj
Opiskeluvalmiuksia tukevat opinnot tietokantaan
=> Add opiskeluvalmiuksia tukevat opinnot

resources/db/hoksit/select_eid.sql, src/db/migration/V1_0001__Create_database.sql, src/oph/ehoks/db/hoks.clj, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj
=> Eh 226 generate eid

src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/hoks/hoks_test.clj
=> Eh 274 db read write for routes

README.md, project.clj, resources/dev/demo-data/hoksit.json, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/import.clj
Demodatan tuonti tietokantaan.
Vanhan tavan poisto (käynnistys ja muistitietokanta)
=> Eh 285 demo data import

src/oph/ehoks/db/postgresql.clj, test/oph/ehoks/hoks/hoks_test.clj
=> Eh 289 empty values

.travis.yml
Just added lein dbmigrate to Travis.
=> added lein dbmigrate to travis

README.md, src/oph/ehoks/main.clj
Migraatioiden ajo käynnistyksen yhteydessä
=> Running migrations

README.md, resources/dev/src/oph/ehoks/json_post_tool.clj, src/oph/ehoks/config.clj, src/oph/ehoks/db/migrations.clj, src/oph/ehoks/external/oph_url.clj
=> Eh 301 better config load

src/oph/ehoks/hoks/schema.clj
Parit regex-tarkistukset schemaan
=> Eh 295 regex schema

src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/handler_test.clj
=> Eh 306 ppto db

resources/dev/src/oph/ehoks/dev_server.clj
=> Add using prod urls on opintopolku environment

resources/dev/dev-routes/kayttooikeus-service_kayttooikeus_kayttaja_virkailija.json, resources/dev/services-oph.properties, resources/dev/src/oph/ehoks/mock_routes.clj, resources/prod/services-oph.properties, src/oph/ehoks/external/cache.clj, src/oph/ehoks/external/cas.clj, src/oph/ehoks/external/kayttooikeus.clj, src/oph/ehoks/handler.clj, src/oph/ehoks/misc/handler.clj, src/oph/ehoks/misc/schema.clj, src/oph/ehoks/virkailija/auth.clj, src/oph/ehoks/virkailija/handler.clj, test/oph/ehoks/misc/handler_test.clj, test/oph/ehoks/virkailija/auth_test.clj
Ticket login virkailijalle.
Ja testiksi yksi route (clear cache)
=> Eh 311 316 ticket login cache clear

resources/db/hoksit/select.sql, resources/db/hoksit/select_eid.sql, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/virkailija/handler.clj
Virkailijan puolelle hoksien käsittelyyn routet.
Huom, nämä on ainoastaan pääkäyttäjälle. Routet ovat devausta varten joten ne saattaapi poistua vielä myöhemmin.
=> Eh 318 oph admin hoks list

src/oph/ehoks/external/cas.clj, src/oph/ehoks/virkailija/auth.clj
=> Use correct services

src/oph/ehoks/external/cas.clj, src/oph/ehoks/virkailija/auth.clj
=> Add logging cas ticket errors

README.md, src/oph/ehoks/main.clj
Migraatioiden ajaminen jarrilla
=> Add using migrations with argument

resources/prod/services-oph.properties
Ehoksille oma backend url, jotta ticket login toimis
=> Change backend url

src/oph/ehoks/external/cas.clj
Vaihdetaan mätsäyksen järjestystä, niin tulee oikea CAS-polku
=> Change matching order

src/oph/ehoks/hoks/handler.clj, test/oph/ehoks/hoks/handler_test.clj
https://jira.csc.fi/browse/EH-321
=> Eh 321 get hoks by opiskeluoikeus

resources/db/select_join.sql, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/handler_test.clj
Puuttuvat ammatilliset osaamiset tietokantaan.
Samalla jonkin verran refaktorointia, kuten HOKSin pääsyoikeudet omaksi middlewareksi.
=> Eh 330 pao db

README.md, resources/dev/src/oph/ehoks/dev_server.clj, src/oph/ehoks/main.clj
Migraatioiden palautus käynnistyksen yhteyteen.
Samalla pieniä koodin siistimisiä.
=> Eh 336 restore migrations

resources/db/oppijat/select_opiskeluoikeudet_by_oppija_oid.sql, src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/oppijaindex.clj, src/oph/ehoks/virkailija/handler.clj, test/oph/ehoks/virkailija/handler_test.clj
Virkailijan oikeuksien tarkistus oppijan tietojen katselussa.
=> Eh 352 virkailija privileges

src/oph/ehoks/hoks/handler.clj, test/oph/ehoks/virkailija/handler_test.clj
Oppijaindeksin haun testejä.
Samalla korjaus virheilmoituksen palautukseen. Lisäksi pari logitusta lisää HOKSin käyttöoikeuksien tarkistukseen.
=> Eh 365 oppijaindex tests

.gitignore, src/oph/ehoks/external/cache.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/virkailija/handler.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/utils.clj, test/oph/ehoks/virkailija/handler_test.clj
Virkailijan puolen HOKSin luontiin tarkoitetut routet.
Samalla pääsyoikeuksien tarkistukset.
=> Eh 368 manual submit routes

src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/hoks/hoks_test.clj
POST ja GET olemassa olevan paikallisen tutkinnon osalle
=> Eh 338 post and get

src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/handler_test.clj
GET ja POST olemassa olevan yhteisen tutkinnon osalle.
=> Eh 339 get and post

README.md, resources/dev/src/oph/ehoks/dev_server.clj, src/oph/ehoks/ehoks_app.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/main.clj
Sovelluksen nimen muutokset:
`ehoks` = oppija 
`ehoks-virkailija` = virkailija
Samalla pari siistimistä.
=> Update app names

src/db/migration/V1_1560322660000__Add_default_value_to_osaamisenhankkimistarve.sql
Lisätty yksi migraatio vielä, joka syöttää oletusarvon uudelle kentälle hoksin juuressa (osaamisen_hankkimisen_tarve).
=> Fix migration error eh 332

resources/dev/services-oph.properties, resources/prod/services-oph.properties, src/oph/ehoks/virkailija/auth.clj, src/oph/ehoks/virkailija/schema.clj, test/oph/ehoks/virkailija/auth_test.clj
=> Eh 383 virkailija session

src/oph/ehoks/virkailija/handler.clj
=> Change to use respond function instead of returning response

src/oph/ehoks/oppija/handler.clj, src/oph/ehoks/virkailija/handler.clj
Routen siirto virkailijan puolelle.
=> Move validation route

resources/dev/services-oph.properties, resources/prod/services-oph.properties, src/oph/ehoks/virkailija/auth.clj
Palautetaan forward virkailijan fronttiin
=> Eh 414 virkailija login fix

oph-configuration/log4j2.properties, resources/dev/log4j2.properties
Logien, Audit ja Access, viestien siivous. Prodissa tulee vain JSON-objekti ja devillä tämän lisäksi tieto, kummasta logista on kyse.
=> Eh 385 audit log clean

project.clj, src/oph/ehoks/logging/audit.clj, test/oph/ehoks/hoks/handler_test.clj
Otettu käyttöön fi.vm.sade.auditlog
=> Eh 406 audit log fix

src/oph/ehoks/main.clj
=> Update oppijaindex on start

src/db/migration/V1_1561617609915__Change_oid_lengths.sql, src/oph/ehoks/hoks/schema.clj
Kasvatetaan oidien maximipituutta
=> Eh 449 oids longer

src/oph/ehoks/user.clj, test/oph/ehoks/user_test.clj
=> Add CRUD for super user

resources/dev/src/oph/ehoks/mock_routes.clj, src/oph/ehoks/virkailija/handler.clj
=> Eh 446 eperusteet error handling

src/oph/ehoks/db/postgresql.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/virkailija/handler.clj
HOKSin luonti ja duplikaatin tarkistus transaktion sisälle
=> Eh 462 hoks transaction

resources/dev/dev-routes/organisaatio-service_rest_organisaatio_v4_findbyoids.json, resources/dev/services-oph.properties, resources/dev/src/oph/ehoks/mock_routes.clj, resources/prod/services-oph.properties, src/oph/ehoks/external/connection.clj, src/oph/ehoks/external/organisaatio.clj, src/oph/ehoks/virkailija/handler.clj
Organisaatioiden hakuun rajapinta
=> Eh 424 user organisations

src/oph/ehoks/logging/access.clj
Poikkeukset myös access logiin
=> Catch and release exceptions

src/oph/ehoks/hoks/schema.clj
=> Remove unused value

src/oph/ehoks/common/api.clj
=> Add logging validation exceptions

.travis.yml
Muutettu .travis.ymliin oracklejdk9 --> openjdk8
=> Eh 509 travis to use openjdk

oph-configuration/config.edn.template
Take DB credentials from new configuration variables.
=> Update config template to use the new DB user for applications

src/oph/ehoks/oppijaindex.clj, src/oph/ehoks/virkailija/middleware.clj
Korjattu toi oikeuksien tsekkaus niin, että ei katso, et pitää olla virkailija (koska voi olla myös oppija), mutta kunhan ei ole palvelu. 
Lisäksi korjattu vaan toi yks middlewaren warn-teksti, kun siinä oli %s ja odotti siihen inputtia, mutta sitä oidia ei ollutkaan sitten siinä, niin siksi toi indeksointi tyssää.
=> Eh 650 fix user type check

src/oph/ehoks/ehoks_app.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/logging/audit.clj, src/oph/ehoks/oppija/handler.clj, src/oph/ehoks/virkailija/handler.clj
Korjattu rajapintojen (palvelukäyttäjien) audit-logitukseen käyttäjän oid ja sessioon service ticket
=> Audit logitus korjaus

doc/hoks.md, resources/dev/demo-data/hoks_ainoastaan_YTOja.json, resources/dev/demo-data/hoksit.json, resources/dev/src/oph/ehoks/mock_routes.clj, src/db/migration/V1_1584510497423__Add_koulutuksen_jarjejestaja_oid_ytooa.sql, src/oph/ehoks/hoks/schema.clj
koulutuksen-jarjestaja-oid added to hankkittavan yhteisen tutkinnon osan osa-alue
=> Eh 857 koulutuksen jarjestaja oid

src/oph/ehoks/hoks/handler.clj
=> Eh 863 refactoring

src/oph/ehoks/db/db_operations/db_helpers.clj, src/oph/ehoks/db/db_operations/hoks.clj, src/oph/ehoks/db/postgresql/aiemmin_hankitut.clj, src/oph/ehoks/db/postgresql/common.clj, src/oph/ehoks/db/postgresql/hankittavat.clj, src/oph/ehoks/db/postgresql/opiskeluvalmiuksia_tukevat.clj, src/oph/ehoks/hoks/aiemmin_hankitut.clj, src/oph/ehoks/hoks/common.clj, src/oph/ehoks/hoks/hankittavat.clj, src/oph/ehoks/hoks/hoks.clj, src/oph/ehoks/hoks/opiskeluvalmiuksia_tukevat.clj, test/oph/ehoks/hoks/hoks_test.clj
Lisätty transaktiot hoksien ja tutkinnon osien luomiseen, muokkaamiseen ja poistamiseen
=> Eh 374 sqs transaktioon

project.clj
Updated clojure 1.10.0 ->  1.10.1. Lots of other dependencies updated too.
=> Deps updated

project.clj
This reverts commit ced3089b611119ac62054925b08043054a52ba19.
=> Revert "Updated lots of dependencies"

doc/hoks.md, src/db/migration/V1_1587628642924__Rename_uuid_To_ShareId.sql, src/oph/ehoks/hoks/aiemmin_hankitut.clj, src/oph/ehoks/hoks/hankittavat.clj, src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/aiemmin_hankitut_handler_test.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/hoks/hankittavat_handler_test.clj, test/oph/ehoks/hoks/hoks_test.clj, test/oph/ehoks/hoks/hoks_test_utils.clj, test/oph/ehoks/oppija/handler_test.clj, test/oph/ehoks/utils.clj, test/oph/ehoks/virkailija/handler_test.clj
Renamed uuid column to module_id. Added module_id to aiemmin_hankitun_yto_osa_alueen_naytto, yhteisen_tutkinnon_osan_osa_alueet, yhteisen_tutkinnon_osan_osa_alueen_naytot, yhteisen_tutkinnon_osan_osa_alueen_osaamisen_hankkimistavat
=> Eh 936 rename

doc/hoks.md, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/partial_hoks_schema.clj, src/oph/ehoks/hoks/schema.clj
Added module-id to GET schemas. Module-id will be made mandatory in an upcoming PR.
=> Eh 936 schema change

doc/hoks.md, src/oph/ehoks/hoks/aiemmin_hankitut.clj, src/oph/ehoks/hoks/hankittavat.clj, src/oph/ehoks/hoks/partial_hoks_schema.clj, src/oph/ehoks/hoks/schema.clj
Made module-id mandatory for GET schemas
=> Eh 936 module id as mandatory

oph-configuration/config.edn.template, oph-configuration/default.edn, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/oppijaindex.clj, src/oph/ehoks/schema.clj, src/oph/ehoks/virkailija/handler.clj, test/oph/ehoks/oppijaindex_test.clj
Tämä tarvitsee taas konfiguraatiolisäykset ympäristöille, lisättävä ehoks_prevent_finished_opiskeluoikeus_updates falseksi kaikkiin.
=> Eh 812 paattyneiden opiskeluoikeuksien paivityksen esto

resources/db/opiskeluoikeudet/select-hankintakoulutus-oids-by-master-oid.sql, src/oph/ehoks/db/db_operations/opiskeluoikeus.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/oppijaindex.clj, test/oph/ehoks/oppijaindex_test.clj, test/oph/ehoks/utils.clj, test/oph/ehoks/virkailija/handler_test.clj
Lisätty endpoint hankintakoulutus opiskeluoikeuksien hakuun ja korjattu hankintakoulutuksien indeksointia
=> Eh 479 hankintakoulutus

src/oph/ehoks/virkailija/system_handler.clj
Uusi endpoint, josta haetaan hoks-id:llä ylläpitonäkymään opiskeluoikeus ja oppija-oid
=> Eh 1013 get opiskeluoikeus with hoks

resources/db/opiskeluoikeudet/select_count_by_koulutustoimija.sql, src/oph/ehoks/db/db_operations/opiskeluoikeus.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/virkailija/system_handler.clj, test/oph/ehoks/oppijaindex_test.clj
Lisätty endpointit opiskeluoikeuden poistamiselle opiskeluoikeus-indeksistä opiskeluoikeuden-oidilla sekä koulutustoimijan-oidilla.
=> Eh 1034 opiskeluoikeuden paivitys

src/oph/ehoks/virkailija/system_handler.clj
A few fixes to opiskeluoikeus index update handlers.
=> Fix system handler

src/oph/ehoks/virkailija/schema.clj, src/oph/ehoks/virkailija/system_handler.clj
Uusi api, joka käy päivittämässä kyseisen oppijan tiedot onr:stä.
=> added new post api for updating oppija-index

resources/db/oppijat/select_oppilaitos_oppijat.sql, src/oph/ehoks/db/db_operations/opiskeluoikeus.clj, src/oph/ehoks/oppijaindex.clj
Jostain syystä tuotannossa haku bugittaa, yritetään qa:lla selvittää mitä pitää tuunata ja palautetaan kunhan saatu ongelma selville.
=> Oppijahaku rollback

resources/dev/demo-data/hoks_ainoastaan_YTOja.json, resources/dev/demo-data/hoks_ainoastaan_paikallisia.json, resources/dev/demo-data/hoks_yksi_tutkinnonosa.json, resources/dev/demo-data/hoksit.json, resources/dev/src/oph/ehoks/mocked_routes/mock_oppijanumerorekisteri_routes.clj
Oppijanumerorekisterin mockidataan lisätty kenttiä. Lisäksi hoksille sähköposti-kenttä.
=> Mock data refinement

resources/dev/ehoks-oph.properties, resources/dev/src/oph/ehoks/dev_server.clj, resources/dev/src/oph/ehoks/mocked_routes/mock_auth_routes.clj, resources/prod/ehoks-oph.properties, src/oph/ehoks/misc/handler.clj, src/oph/ehoks/misc/schema.clj, src/oph/ehoks/oppija/auth_handler.clj, test/oph/ehoks/oppija/auth_handler_test.clj
Cas-oppijan urleja lisätty. Placeholder endpoint cas-kirjautumiselle joka tällä hetkellä heittää poikkeuksen. Environment route palautamaan cas-oppija-login osoitteen. Mock route cas-oppijan loginille.
=> Eh 984 oppija cas placeholder

src/oph/ehoks/external/cas.clj, src/oph/ehoks/oppija/auth_handler.clj, test/oph/ehoks/oppija/auth_handler_test.clj
Käyttäjän tietojen haku oppijanumerorekisteristä cas:in validoinnista saaduilla tiedoilla. Tietojen tallennus sessioon.
=> Eh 984 cas oppija user info

resources/dev/demo-data/hoks_ainoastaan_ammatillisia.json, resources/dev/dev-routes/eperusteet-service_api_tutkinnonosat_telma.json, src/oph/ehoks/common/api.clj
Lisätty stacktrace logeille, tällä kertaa niin että stacktrace tulee logille yhtenä rivinä. Lisäksi pr:ssä mukana testidatan lisäyksiä.
=> Stacktrace to logs

src/oph/ehoks/virkailija/system_handler.clj
Uusi endpoint aloituskysely herätteiden manuaaliseen lähettämiseen
=> Eh 1100 aloitusherate yllapitoon

resources/dev/demo-data/hoksit.json, resources/dev/dev-routes/eperusteet-service_api_perusteenosat_3708884_osaalueet.json, resources/dev/dev-routes/eperusteet-service_api_tutkinnonosat_400014.json, resources/dev/src/oph/ehoks/mocked_routes/mock_eperusteet_routes.clj
=> Test data for osa alue bug

resources/dev/demo-data/hoksit.json, src/oph/ehoks/hoks/hoks.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/hoks/test_data.clj
Osaamisen saavuttamisen päivämäärän tyhjennys jos se annetaan tyhjänä manuaalikälistä.
=> Eh 1118 null osaamisen saavuttamisen pvm

oph-configuration/default.edn, resources/db/heratepalvelu/select_paattyneet_tyoelamajaksot_hato.sql, resources/db/heratepalvelu/select_paattyneet_tyoelamajaksot_hpto.sql, resources/db/heratepalvelu/select_paattyneet_tyoelamajaksot_hyto.sql, src/db/migration/V1_1617990609400__Add_tep_kasitelty_to_osaamisen_hankkimistapa.sql, src/oph/ehoks/db/db_operations/hoks.clj, src/oph/ehoks/external/aws_sqs.clj, src/oph/ehoks/heratepalvelu/herate_handler.clj, src/oph/ehoks/heratepalvelu/heratepalvelu.clj, src/oph/ehoks/oppija/auth_handler.clj
Työelämäpalautteen rajapintoja
=> Eh 778 tep

src/oph/ehoks/hoks/schema.clj
Koodista löytyy TODO-kommentteja, koska tämä revertoidaan pian (toivottavasti ensi viikolla).
=> Oppisopimuksen perusta -vaatimus kommentoitu pois

resources/db/hoksit/select_osaamisen_hankkimistavat_by_hoks_id_and_tunniste.sql, src/oph/ehoks/db/postgresql/hankittavat.clj, test/oph/ehoks/hoks/handler_test.clj, test/oph/ehoks/hoks/test_data.clj
- Pieni parannus yksiloiva-tunniste queryyn ja testi yksiloiva-tunnisteen toiminnan varmistamiseksi.
- Lisätään updated_at arvo kun päivitetään osaamisen hankkimistapaa.
=> yksiloiva-tunniste query

src/db/migration/V1_1666339400990__Add_TUVA_opiskeluoikeus_to_HOKS.sql, src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/hoks/vipunen_schema.clj, test/oph/ehoks/hoks/hoks_handler_test.clj, test/oph/ehoks/hoks/hoks_save_test.clj
https://jira.eduuni.fi/browse/OY-3815
=> OY-3815 Add tuva-opiskeluoikeus-oid to hoks

README.md, doc/code-guidelines.md
Tämä kuittaa tiketin [EH-1442](https://jira.eduuni.fi/browse/EH-1442) ja on edellytys tehtävälle PR checklistille (https://github.com/Opetushallitus/ehoks/pull/532).
=> Lisätty dokumentaatio koodikäytänteistä

src/oph/ehoks/heratepalvelu/herate_handler.clj
Disabloidaan yhteystietojen siivous Herätepalvelun ongelmien selvityksen ajaksi.
https://jira.eduuni.fi/browse/EH-1504
=> EH-1504: Yhteystietojen siivouksen disablointi

src/oph/ehoks/hoks/schema.clj, test/oph/ehoks/hoks/hoks_handler_test.clj, test/oph/ehoks/hoks/hoks_parts/parts_test_data.clj, test/oph/ehoks/hoks/test_data.clj
Validoidaan osa-aikaisuustieto, mikäli työpaikkajakson loppupäivä on 1.7.2023 tai myöhemmin.
https://jira.eduuni.fi/browse/OY-4264
=> OY-4264: Osa-aikaisuustiedon validointi

src/oph/ehoks/heratepalvelu/heratepalvelu.clj
OY-4249:ssa selviteltiin, miksei oppijanumero ollut päivittynyt eHOKSissa, vaikka ONR-päivitys oli käsitelty access login perusteella.  Tämä PR lisää lokitusta sen verran, että tehtiinpä ONR-päivitykselle mitä tahansa, aina lokitetaan vähintään, mitä päätettiin tehdä.
https://jira.eduuni.fi/browse/OY-4249
=> Add logging to tell why ONR update was not acted upon

.gitignore, Makefile, scripts/create-cas-tgt.sh, scripts/curl-with-cas.sh
- Exclude json-schema-viewer.json from ctags generation because it's generated and creates false positives for definitions
- Publish scripts that show how CAS authentication and CAS authenticated calls are done
- No related ticket
=> Some developer utility improvements (no user visible effect)

resources/dev/demo-data/hoksit.json, src/db/migration/V1_1691683397331__Add_opiskeluoikeus_start,_projected_end,_and_update_date.sql, src/oph/ehoks/db/db_operations/opiskeluoikeus.clj, src/oph/ehoks/db/queries.clj, src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, src/oph/ehoks/hoks/middleware.clj, src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/middleware.clj, src/oph/ehoks/oppijaindex.clj, src/oph/ehoks/virkailija/handler.clj, src/oph/ehoks/virkailija/middleware.clj, test/oph/ehoks/hoks/hoks_parts/parts_test_data.clj, test/oph/ehoks/hoks/invalid_hoks_handler_test.clj, test/oph/ehoks/oppijaindex_test.clj, test/oph/ehoks/utils.clj
- index new fields include alkamispäivä and arvioituPäättymispäivä
- create mechanism for updating outdated opiskeluoikeudet in index upon saving new HOKS
- check that osaamisenhankkimistapa is at most 5 years long
- check that osaamisenhankkimistapa doesn't start before alkamispäivä nor end after arvioituPäättymispäivä
Katso myös yksittäisten commitien selitykset!
https://jira.eduuni.fi/browse/OY-3945
=> Comparing osaamisenhankkimistapa dates against opiskeluoikeus dates

scripts/curl-with-cas.sh, scripts/upload-hoks.sh
- curl-with-cas.sh: parameterise for SERVICE so that it can be used to call other services
- upload-hoks.sh: don't output headers so the output is easier to parse
=> Improve helper scripts

src/oph/ehoks/external/cas.clj
Jos CAS service ticketin sisältämä request epäonnistuu, responsen ollessa HTTP 401 Unauthorized, kokeillaan samaa requestia uudestaan uudella Ticket Granting Ticketilla (TGT).
On hieman epävarmaa, korjaako tämä muutos tuon nykyisen ongelman (auttoi ainakin Vardan tapauksessa, kts. EH-1557 kommentit). Mielestäni tätä voisi kuitenkin kokeilla QA:lla ja katsoa eliminoiko nuo HTTP 401 Unauthorized -virheet, ja jos näkyy toimivan, niin voisin jatkaa tämän kanssa kirjoittamalla myös yksikkötestit.
https://jira.eduuni.fi/browse/EH-1557
=> Add CAS retry logic in case of HTTP 401 errors

src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/hoks/hoks.clj, src/oph/ehoks/hoks/schema.clj, src/oph/ehoks/middleware.clj, src/oph/ehoks/opiskelijapalaute.clj, src/oph/ehoks/virkailija/handler.clj, test/oph/ehoks/hoks/hoks_handler_test.clj, test/oph/ehoks/virkailija/handler_test.clj
Middleware, joka antaa opiskeluoikeuden tiedot tarjolle jo skeematarkistusta varten, ja lisäehto `osa-aikaisuustieto-valid?`-tarkistukseen.
https://jira.eduuni.fi/browse/OY-4433
=> Only check osa-aikaisuus for non-TELMA opiskeluoikeudet

doc/tyopaikkajaksojen-kestojen-laskenta.md
Dokumentaatiota 2022-2023 rahoituskauden työpaikkajaksoille tehdyistä kestojen korjauksista.
https://jira.eduuni.fi/browse/EH-1562
=> Dokumentaatio rahoituskauden 2022-2023 työpaikkajaksojen kestojen korjauksista

src/oph/ehoks/schema/oid.clj
Weeklyssa puhuttu OrganisaatioOID schema korjaus. Liittyy tikettiin https://jira.eduuni.fi/browse/OY-4634.
=> Make OrganisaatioOID use one regexp

.github/pull_request_template.md
Lisätään pr templateen muistutukset siitä, että annetaan homma OPH:lle testattavaksi
=> testing actions agreed upon in weekly

.github/workflows/build.yml, README.md, src/oph/ehoks/ehoks_app.clj, src/oph/ehoks/palaute/handler.clj
Lisää uusi backend-palvelu ehoks-palaute
https://jira.eduuni.fi/browse/EH-1581
=> EH-1581: Lisää uusi backend-palvelu ehoks-palaute

.github/workflows/build.yml, src/oph/ehoks/palaute/handler.clj
lein checkall taas käyttöön CI:llä
https://jira.eduuni.fi/browse/EH-1631
=> EH-1631: lein checkall taas käyttöön CI:llä

resources/public/json-viewer/styles/json-schema-viewer.min.css
Koska json-schema-viewer'n riippuvuudet päivittyivät, se pitää muodostaa uusiksi.  (En ole ihan varma, miksei buildi tee niin.)  Tulokset ovat tässä PR:ssä.
=> Run `grunt prod` with new dependencies and commit the result

resources/dev/demo-data/anonymised-example-1.json, resources/dev/demo-data/anonymised-example-2.json, resources/dev/demo-data/hoks_ainoastaan_YTOja.json, resources/dev/demo-data/hoks_ainoastaan_ammatillisia.json, resources/dev/demo-data/hoks_ainoastaan_paikallisia.json, resources/dev/demo-data/hoks_tuva.json, resources/dev/demo-data/hoks_yksi_tutkinnonosa.json, resources/dev/demo-data/hoksit.json
HOKSeja ei ole enää vähään aikaan voinut helposti testata lokaalisti, koska esimerkki-HOKSit lähdekoodissa eivät ole enää valideja (tai siis, eivät koskaan olleetkaan, mutta nyt bäkkäri myös huomaa sen).
- korjattu kaikki validaatiovirheet
- siroteltu eri esimerkki-HOKSit eri opiskeluoikeuksille
- lisätty pari tuotannosta anonymisoitua HOKSia esimerkkidataksi
https://jira.eduuni.fi/browse/EH-1652
=> EH-1652: Fix validation errors in demo data

src/db/migration/V1_1710848004576__Palautteet_skeema.sql
Palautteet-skeema
https://jira.eduuni.fi/browse/EH-1582
=> EH-1582: Palautteet-skeema

src/oph/ehoks/db/db_operations/hoks.clj
Vanha `delete-opiskelijan-yhteystiedot!` ei ota huomioon, että opiskeluoikeus on voinut hävitä.  Nostettu ExceptionInfo pääsee läpi middlewareille asti ja ilmeisesti muutetaan 400-virheeksi.  Tämä PR muuttaa siten, että hävinnyt opiskeluoikeus oletetaan päättyneeksi.
https://jira.eduuni.fi/browse/EH-1514
=> delete-opiskelijan-yhteystiedot!: treat missing opiskeluoikeus as ended

src/oph/ehoks/heratepalvelu/herate_handler.clj
Eroon vastausten validointivirheistä herate-handlerissa.  Skeemoja ei ollut muistettu kääriä yleiseen restful-formaattiin.
=> Fix response schemata for heratepalvelu-handler

.gitignore, Makefile, README.md, pom.xml, project.clj, resources/dev/src/oph/ehoks/mocked_routes/mock_organisaatio_routes.clj, resources/dev/src/oph/ehoks/mocked_routes/mock_routes.clj, resources/test/config/log4j2.properties, scripts/upload-hoks.sh, src/oph/ehoks/external/organisaatio.clj, src/oph/ehoks/hoks.clj, src/oph/ehoks/opiskeluoikeus/suoritus.clj, src/oph/ehoks/palaute/opiskelija.clj, test/oph/ehoks/db/opiskelijan_yhteystiedot_test.clj, test/oph/ehoks/external/organisaatio_test.clj, test/oph/ehoks/oppija/handler_test.clj, test/oph/ehoks/oppija/share_handler_test.clj, test/oph/ehoks/test_utils.clj
- don't do heräte SQS sends or DB inserts in a future, because it will swallow exceptions
- fix `suoritus/kieli` to be tolerant of missing information
- add logging for `:resend?` case
https://jira.eduuni.fi/browse/EH-1583
=> EH-1583: Fix heräte creation and make its debugging easier

src/oph/ehoks/palaute/opiskelija.clj, test/oph/ehoks/palaute/opiskelija_test.clj
Mergetään tämä, koska siitä aiheutuu kaikkein todennäköisimmin konflikteja jatkokehityksen kanssa
https://jira.eduuni.fi/browse/EH-1585
=> EH-1585 aja muutokset transaktiossa

src/oph/ehoks/palaute/opiskelija.clj, test/oph/ehoks/palaute/opiskelija_test.clj
Puuttuvat säännöt, miksi palautetta ei kerätä
https://jira.eduuni.fi/browse/EH-1692
=> EH-1692: terminal state and external funding as reasons of not creating palaute

resources/db/heratepalvelu/select_paattyneet_tyoelamajaksot_hato.sql, resources/db/heratepalvelu/select_paattyneet_tyoelamajaksot_hpto.sql, resources/db/heratepalvelu/select_paattyneet_tyoelamajaksot_hyto.sql, src/oph/ehoks/external/aws_sqs.clj
Lisätään yksilöivät tunnisteet jaksojen tietoihin Herätepalvelussa nollakestojen korjaamista varten. eHOKsin osalta aika pienet muutokset kyseessä siis, Herätepalvelun puolella enemmän tekemistä. Meillä ei näköjään ole entuudestaan yhtään testejä työpaikkajaksojen poiminnalle Herätepalveluun lähetystä varten. :smiling_face_with_tear: En kuitenkaan näin pientä muutosta varten lähtisi kattavia testejä rakentamaan, varsinkin kun jaksojen Herätepalveluun lähetys tullaan poistamaan jonkin ajan kuluttua palaute-backendin käyttöönoton myötä.
https://jira.eduuni.fi/browse/EH-1697
=> EH-1697: Työpaikkajakson yksilöivä tunniste tallentumaan Herätepalveluun

src/oph/ehoks/hoks/handler.clj, src/oph/ehoks/oppijaindex.clj
Lokiviestien parantamisesta oli kuin olikin apua debuggaamisessa:
```
2024-08-15T16:38:59.952+03 ERROR [qtp2012345295-41] compojure.api.exception:0 - Error while fetching opiskeluoikeus `{:oid "1.2.246.562.15.25075474921"}` from Koski. Koski-virhekoodi is `badRequest.queryParam.virheellinenOpiskeluoikeusOid`.
clojure.lang.ExceptionInfo: Error while fetching opiskeluoikeus `{:oid "1.2.246.562.15.25075474921"}` from Koski. Koski-virhekoodi is `badRequest.queryParam.virheellinenOpiskeluoikeusOid`.
at oph.ehoks.external.koski$get_opiskeluoikeus_BANG_.invokeStatic(koski.clj:100) ~[ehoks-virkailija.jar:?]
at oph.ehoks.external.koski$get_opiskeluoikeus_BANG_.invoke(koski.clj:88) ~[ehoks-virkailija.jar:?]
at oph.ehoks.palaute$hankintakoulutuksen_toteuttaja_BANG_.invokeStatic(palaute.clj:87) …
```
=> Make `get-hankintakoulutus-oids-by-master-oid` actually return OIDs

.editorconfig
Erottelua sisennyksissä eri tiedostotyyppien välillä.
=> Changes to `.editorconfig`

resources/dev/dev-routes/kayttooikeus-service_kayttooikeus_kayttaja_virkailija.json, resources/dev/dev-routes/koski_api_opiskeluoikeus_1.2.246.562.15.13312692646.json, resources/dev/dev-routes/koski_api_opiskeluoikeus_1.2.246.562.15.76811932037.json, resources/dev/dev-routes/organisaatio-service_rest_organisaatio_v4_1.2.246.562.10.21122461771.json, resources/dev/src/oph/ehoks/mocked_routes/mock_arvo_routes.clj, resources/dev/src/oph/ehoks/mocked_routes/mock_koski_routes.clj, resources/dev/src/oph/ehoks/mocked_routes/mock_organisaatio_routes.clj, resources/dev/src/oph/ehoks/mocked_routes/mock_routes.clj, src/oph/ehoks/external/organisaatio.clj, src/oph/ehoks/schema/oid.clj
create example data that makes local testing of Arvo kyselylinkki creation calls possible.
https://jira.eduuni.fi/browse/EH-1584
=> EH-1584: example data improvements

Makefile, README.md, scripts/ci-scripts/run_postgres.sh, scripts/postgres-docker/Dockerfile, src/oph/ehoks/db.clj, src/oph/ehoks/db/sql/palaute.sql, src/oph/ehoks/palaute/tyoelama.clj, test/oph/ehoks/palaute/tyoelama_test.clj
Kaikenlaisia parannuksia olemassa olevaan koodiin, jotka on tulleet vastaan EH-1584:a toteuttaessa.
- PG-upgrade tarvitaan, jotta WITH-lausekkeeseen voi liittää optimoinnin mahdollistavan AS NOT MATERIALIZED -lisämääreen
- PgArray-sovitin tarvitaan, jotta HugSQL:sta pystyy palauttamaan array-muotoisia kenttiä tuloksissa
https://jira.eduuni.fi/browse/EH-1584
=> EH-1584: small improvements

resources/dev/src/oph/ehoks/mocked_routes/mock_arvo_routes.clj, src/oph/ehoks/db/dynamodb.clj, src/oph/ehoks/db/sql/palaute.sql, src/oph/ehoks/palaute.clj, src/oph/ehoks/palaute/handler.clj, src/oph/ehoks/palaute/opiskelija.clj, src/oph/ehoks/palaute/scheduler.clj, src/oph/ehoks/palaute/tyoelama.clj, test/oph/ehoks/palaute/opiskelija_test.clj
- handlers for calling Arvo for opiskelijapalaute that doesn't yet have kysely but should
- API for starting this manually
- scheduler invocation for starting this periodically
https://jira.eduuni.fi/browse/EH-1584
=> EH-1584: Call Arvo and sync data to Heratepalvelu for `odottaa_kasittelya` heratteet

.github/workflows/create-lampi-export-runner-image.yml
Korjaus Lampi-exportterin luontiin
=> Fix lampi build workflow

src/oph/ehoks/palaute.clj, src/oph/ehoks/palaute/opiskelija.clj
Yritetään selvittää miksi joskus tehdään insert kun pitäisi tulla update olemassa olevalle palautteelle
https://jira.eduuni.fi/browse/EH-1725
=> EH-1725: add logging about upsert logic

src/oph/ehoks/palaute/opiskelija.clj
Lisää debuggausta: koska kerran duplikaattitapauksissa existing-heratteet on tyhjä, lokitetaan miten se muodostuu.
https://jira.eduuni.fi/browse/EH-1725
=> EH-1725: add logging for existing-heratteet!

src/oph/ehoks/external/aws_sqs.clj, src/oph/ehoks/palaute/handler.clj
Miscellaneous fixes for taking palaute-backend to use in production, part 1
https://jira.eduuni.fi/browse/EH-1711
=> EH-1711: Miscellaneous fixes for taking palaute-backend to use in production, part 1

scripts/lampi-export/Dockerfile, scripts/lampi-export/send-error-message.sh
Lähetä slack-notsku jos skripti epäonnistuu
OY-4608
=> OY-4608: Lähetä slack-notsku jos skripti epäonnistuu

src/db/migration/V1_1735564733853__Reporting_timestamp.sql
Aikaleima reporting-skeeman päivitykseen
OY-4608
=> OY-4608: Aikaleima reporting-skeeman päivitykseen

src/db/migration/V1_1736423100280__palaute_duplicate_cleanup.sql
These records have been accumulating because of mistakes in palaute logic, but they really shouldn't be there.  Every HOKS should have one or zero aloituskysely, one or zero päättökysely (either valmistuneet or osia_suorittaneet) and one or zero työelämäkysely for each of its työpaikkajaksot.
Katsoin samalla, minkä verran kuukausittain näitä poistettavia on (tuotannossa).
```sql
ehoks=> select extract(month from created_at), count(*) from palautteet p1 where exists (select 1 from palautteet p2 where p1.hoks_id=p2.hoks_id and p1.kyselytyyppi=p2.kyselytyyppi and p1.jakson_yksiloiva_tunniste=p2.jakson_yksiloiva_tunniste and p1.created_at < p2.created_at) group by extract(month from created_at);
extract,count
7,12377
8,116636
9,32472
ehoks=> select extract(month from created_at), count(*) …
```
=> EH-1757: remove duplicate palaute records from DB

.github/workflows/build.yml, resources/db/hoksit/select_kyselylinkit_by_oppija_oid.sql, src/oph/ehoks/db/db_operations/hoks.clj, test/oph/ehoks/palaute/opiskelija_test.clj
Seurantaparametri kyselylinkkeihin - hae kyselylinkkejä myös eHOKSissa muodostetuista palautteista
https://jira.eduuni.fi/browse/EH-1750
=> EH-1750: Seurantaparametri kyselylinkkeihin - hae kyselylinkkejä myös eHOKSissa muodostetuista palautteista

resources/dev/ehoks-oph.properties, resources/prod/ehoks-oph.properties, src/oph/ehoks/external/eperusteet.clj
https://jira.eduuni.fi/browse/EH-1776
=> Fix ePerusteet API incompatibility

doc/integraatiot.md
https://jira.eduuni.fi/browse/OY-5013
=> Add documentation about integrations

src/oph/ehoks/palaute/opiskelija.clj, src/oph/ehoks/palaute/tapahtuma.clj, src/oph/ehoks/palaute/vastaajatunnus.clj, test/oph/ehoks/palaute/opiskelija_test.clj, test/oph/ehoks/palaute/tyoelama_test.clj
Add details to:
- error logging (failed arvo requests)
- phase logging (info level logs about what we're doing)
- tapahtuma logging (request id to tapahtumat of palaute handling)
=> EH-1732: logging improvements

src/oph/ehoks/palaute/scheduler.clj
Näyttäis siltä, että palaute-backendin päivittäinen ajo ei oo käynnistynyt alun jälkeen -> selvitetään suoritetaanko ajo nätisti loppuun asti.
=> EH-1798: also log the end of daily actions to see it was reached

oph-configuration/config.edn.template, src/db/migration/V1_1742311147193__Mark_old_palautteet_as_deleted.sql
https://jira.eduuni.fi/browse/EH-1711 kohta 4
=> EH-1711: put herätepalvelu table names in config template

doc/integraatiot.md, doc/lampi-siirto.md
=> Lampi-siirron dokumentointi

src/oph/ehoks/schema/oid.clj, test/oph/ehoks/schema/oid_test.clj
https://jira.eduuni.fi/browse/EH-1785
=> Add new oppija and organisaatio OID nodes for test environments

src/oph/ehoks/hoks/handler.clj
Lisätään näkyvyyttä siihen, miksi mikäkin HOKS päätyy failed-ids:iin Vipusen kyselyssä.
https://jira.eduuni.fi/browse/EH-1788
=> EH-1788: add logging for validation errors in Vipunen HOKS fetches

src/oph/ehoks/palaute/scheduler.clj
Vielä on varaa kasvattaa batch sizea, 2500 -> 3000.
=> Increace `palaute/reinit-palautteet-for-uninitiated-hokses!` batch size again

src/oph/ehoks/palaute/scheduler.clj, src/oph/ehoks/utils.clj
Koska kaikki muu näyttäisi toimivan kuin tämä eräajo, varmistetaan ettei se jää jumiin ja lokitetaan poikkeus, jos jää.  Lisää perusteluita tiketin [havainnoissa](https://jira.eduuni.fi/browse/EH-1818?focusedId=322802&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-322802).
https://jira.eduuni.fi/browse/EH-1818
=> EH-1818: add timeout to reinit-uninitiated-hoksen!

src/oph/ehoks/hoks/handler.clj
https://jira.eduuni.fi/browse/EH-1816
=> Fix `PATCH /hoks/kyselylinkki`

src/oph/ehoks/palaute/opiskelija.clj
Tän pitäisi korjata SMS-viestien lähetys.
https://jira.eduuni.fi/browse/EH-1829
=> Add `sms-lahetystila` to amisherate record

src/oph/ehoks/palaute/tyoelama.clj, test/oph/ehoks/hoks/hoks_save_test.clj, test/oph/ehoks/palaute/tyoelama_test.clj
Asetusmuutoksen myötä niputus tehdään 1.7.2025 alkaen kerran kuussa, kuukauden ensimmäisena päivänä.
https://jira.eduuni.fi/browse/EH-1808
=> EH-1808: Make niputus occur once a month
